export type Req = { key: string; label: string; tag: string }

export const BRIEF_REQUIREMENTS: Record<string, Req[]> = {
  _common: [
    { key: 'brief_smart_home',       label: 'Умный дом',                  tag: '#smart_home'          },
    { key: 'brief_work_from_home',   label: 'Кабинет / работа дома',      tag: '#home_office'         },
    { key: 'brief_soundproofing',    label: 'Шумоизоляция',               tag: '#soundproofing'       },
    { key: 'brief_pets',             label: 'Питомцы',                    tag: '#pets_friendly'       },
    { key: 'brief_pet_zone',         label: 'Специальная зона для питомца',tag: '#pet_zone'            },
    { key: 'brief_pet_wash',         label: 'Мойка для животных',         tag: '#pet_wash'            },
    { key: 'brief_storage',          label: 'Много хранения',             tag: '#storage_plus'        },
    { key: 'brief_accessibility',    label: 'Доступная среда (МГН)',       tag: '#accessibility'       },
    { key: 'brief_climate',          label: 'Система климат-контроля',    tag: '#climate_control'     },
    { key: 'brief_biophilic',        label: 'Биофильный дизайн / растения',tag: '#biophilic'          },
    { key: 'brief_indoor_garden',    label: 'Зимний сад / фитостена',     tag: '#indoor_garden'       },
    { key: 'brief_natural_light',    label: 'Максимум естественного света',tag: '#natural_light'      },
    { key: 'brief_circadian_light',  label: 'Циркадное освещение',        tag: '#circadian_lighting'  },
    { key: 'brief_air_quality',      label: 'Очистка / рекуперация воздуха',tag: '#air_quality'       },
    { key: 'brief_water_filter',     label: 'Очистка воды',               tag: '#water_filtration'    },
    { key: 'brief_eco_materials',    label: 'Экологичные материалы',      tag: '#eco_materials'       },
    { key: 'brief_wellness',         label: 'Велнес / нейровелнес интерьер',tag: '#wellness_design'   },
    { key: 'brief_meditation',       label: 'Зона медитации / практик',   tag: '#meditation_zone'     },
    { key: 'brief_no_formaldehyde',  label: 'Без формальдегида / VOC',    tag: '#healthy_materials'   },
    { key: 'brief_guest_bedroom',    label: 'Гостевая спальня',           tag: '#guest_bedroom'       },
  ],

  apartment: [
    { key: 'brief_kids_room',        label: 'Детская / зоны детей',       tag: '#kids_room'           },
    { key: 'brief_kids_grow',        label: 'Мебель растёт с ребёнком',   tag: '#kids_grow_furniture' },
    { key: 'brief_home_gym',         label: 'Фитнес-зона',                tag: '#home_gym'            },
    { key: 'brief_home_cinema',      label: 'Домашний кинотеатр',         tag: '#home_cinema'         },
    { key: 'brief_chef_kitchen',     label: 'Проф. кухня',                tag: '#chef_kitchen'        },
    { key: 'brief_kitchen_island',   label: 'Кухонный остров',            tag: '#kitchen_island'      },
    { key: 'brief_sauna',            label: 'Хаммам / сауна',             tag: '#sauna_hammam'        },
    { key: 'brief_gallery',          label: 'Коллекция / галерея',        tag: '#art_gallery'         },
    { key: 'brief_walk_in_closet',   label: 'Гардеробная',                tag: '#walk_in_closet'      },
    { key: 'brief_balcony',          label: 'Балкон / лоджия',            tag: '#balcony'             },
    { key: 'brief_open_plan',        label: 'Открытая планировка',        tag: '#open_plan'           },
    { key: 'brief_master_bedroom',   label: 'Мастер-спальня',             tag: '#master_bedroom'      },
    { key: 'brief_library',          label: 'Библиотека / кабинет',       tag: '#home_library'        },
    { key: 'brief_panic_room',       label: 'Комната безопасности',       tag: '#panic_room'          },
    { key: 'brief_utility_room',     label: 'Постирочная / хозблок',      tag: '#utility_laundry'     },
    { key: 'brief_smart_bathroom',   label: 'Умная ванная',               tag: '#smart_bathroom'      },
    { key: 'brief_acoustic_panels',  label: 'Акустические панели',        tag: '#acoustic_panels'     },
    { key: 'brief_hidden_storage',   label: 'Скрытые системы хранения',   tag: '#hidden_storage'      },
    { key: 'brief_floor_heating',    label: 'Тёплые полы',                tag: '#floor_heating'       },
    { key: 'brief_dressing_room',    label: 'Отдельная примерочная',      tag: '#dressing_room'       },
  ],

  penthouse: [
    { key: 'brief_kids_room',        label: 'Детская',                    tag: '#kids_room'           },
    { key: 'brief_home_gym',         label: 'Тренажёрный зал',            tag: '#home_gym'            },
    { key: 'brief_home_cinema',      label: 'Домашний кинотеатр',         tag: '#home_cinema'         },
    { key: 'brief_chef_kitchen',     label: 'Проф. кухня',                tag: '#chef_kitchen'        },
    { key: 'brief_sauna',            label: 'Хаммам / сауна',             tag: '#sauna_hammam'        },
    { key: 'brief_gallery',          label: 'Коллекция / галерея',        tag: '#art_gallery'         },
    { key: 'brief_wine_cellar',      label: 'Винный погреб / бар',        tag: '#wine_cellar'         },
    { key: 'brief_walk_in_closet',   label: 'Гардеробная',                tag: '#walk_in_closet'      },
    { key: 'brief_master_bedroom',   label: 'Мастер-спальня',             tag: '#master_bedroom'      },
    { key: 'brief_rooftop_terrace',  label: 'Терраса на крыше',           tag: '#rooftop_terrace'     },
    { key: 'brief_rooftop_garden',   label: 'Сад на крыше',               tag: '#rooftop_garden'      },
    { key: 'brief_pool',             label: 'Бассейн / джакузи',          tag: '#pool_jacuzzi'        },
    { key: 'brief_library',          label: 'Библиотека / кабинет',       tag: '#home_library'        },
    { key: 'brief_open_plan',        label: 'Открытая планировка',        tag: '#open_plan'           },
    { key: 'brief_smart_bathroom',   label: 'Умная ванная',               tag: '#smart_bathroom'      },
    { key: 'brief_utility_room',     label: 'Постирочная',                tag: '#utility_laundry'     },
    { key: 'brief_staff_room',       label: 'Комната персонала',          tag: '#staff_quarters'      },
    { key: 'brief_hidden_storage',   label: 'Скрытые системы хранения',   tag: '#hidden_storage'      },
    { key: 'brief_acoustic_panels',  label: 'Акустические панели',        tag: '#acoustic_panels'     },
    { key: 'brief_floor_heating',    label: 'Тёплые полы',                tag: '#floor_heating'       },
  ],

  house: [
    { key: 'brief_kids_room',        label: 'Детская',                    tag: '#kids_room'           },
    { key: 'brief_kids_grow',        label: 'Мебель растёт с ребёнком',   tag: '#kids_grow_furniture' },
    { key: 'brief_home_gym',         label: 'Тренажёрный зал',            tag: '#home_gym'            },
    { key: 'brief_home_cinema',      label: 'Кинозал',                    tag: '#home_cinema'         },
    { key: 'brief_chef_kitchen',     label: 'Проф. кухня',                tag: '#chef_kitchen'        },
    { key: 'brief_sauna',            label: 'Баня / сауна',               tag: '#sauna_house'         },
    { key: 'brief_wine_cellar',      label: 'Винный погреб',              tag: '#wine_cellar'         },
    { key: 'brief_fireplace',        label: 'Камин',                      tag: '#fireplace'           },
    { key: 'brief_pool',             label: 'Бассейн / хот-таб',          tag: '#pool_hottub'         },
    { key: 'brief_garage',           label: 'Гараж / мастерская',         tag: '#garage_workshop'     },
    { key: 'brief_ev_charging',      label: 'Зарядка для электромобиля',  tag: '#ev_charging'         },
    { key: 'brief_guest_house',      label: 'Гостевой дом',               tag: '#guest_house'         },
    { key: 'brief_garden',           label: 'Ландшафт / сад',             tag: '#garden'              },
    { key: 'brief_greenhouse',       label: 'Теплица / оранжерея',        tag: '#greenhouse'          },
    { key: 'brief_kitchen_garden',   label: 'Кухонный огород / грядки',   tag: '#kitchen_garden'      },
    { key: 'brief_kids_playground',  label: 'Детская площадка',           tag: '#kids_playground'     },
    { key: 'brief_bbq',              label: 'Барбекю / летняя кухня',     tag: '#bbq_summer'          },
    { key: 'brief_walk_in_closet',   label: 'Гардеробная',                tag: '#walk_in_closet'      },
    { key: 'brief_gallery',          label: 'Коллекция / галерея',        tag: '#art_gallery'         },
    { key: 'brief_library',          label: 'Библиотека / кабинет',       tag: '#home_library'        },
    { key: 'brief_home_automation',  label: 'Система безопасности',       tag: '#home_security'       },
    { key: 'brief_solar',            label: 'Солнечные панели / автономия',tag: '#solar_energy'       },
    { key: 'brief_rainwater',        label: 'Сбор дождевой воды',         tag: '#rainwater_harvest'   },
    { key: 'brief_animals_stable',   label: 'Конюшня / вольер',           tag: '#animals_stable'      },
    { key: 'brief_mud_room',         label: 'Грязный тамбур / раздевалка',tag: '#mud_room'            },
    { key: 'brief_staff_room',       label: 'Комната персонала',          tag: '#staff_quarters'      },
    { key: 'brief_smart_bathroom',   label: 'Умная ванная',               tag: '#smart_bathroom'      },
    { key: 'brief_utility_room',     label: 'Постирочная / хозблок',      tag: '#utility_laundry'     },
    { key: 'brief_floor_heating',    label: 'Тёплые полы',                tag: '#floor_heating'       },
    { key: 'brief_water_features',   label: 'Водные объекты (пруд/ручей)',tag: '#water_features'      },
    { key: 'brief_outdoor_shower',   label: 'Уличный душ',                tag: '#outdoor_shower'      },
  ],

  townhouse: [
    { key: 'brief_kids_room',        label: 'Детская',                    tag: '#kids_room'           },
    { key: 'brief_home_gym',         label: 'Фитнес-зона',                tag: '#home_gym'            },
    { key: 'brief_home_cinema',      label: 'Домашний кинотеатр',         tag: '#home_cinema'         },
    { key: 'brief_chef_kitchen',     label: 'Проф. кухня',                tag: '#chef_kitchen'        },
    { key: 'brief_sauna',            label: 'Хаммам / сауна',             tag: '#sauna_hammam'        },
    { key: 'brief_wine_cellar',      label: 'Винный погреб',              tag: '#wine_cellar'         },
    { key: 'brief_fireplace',        label: 'Камин',                      tag: '#fireplace'           },
    { key: 'brief_terrace',          label: 'Патио / терраса',            tag: '#terrace_patio'       },
    { key: 'brief_garage',           label: 'Гараж',                      tag: '#garage'              },
    { key: 'brief_ev_charging',      label: 'Зарядка для электромобиля',  tag: '#ev_charging'         },
    { key: 'brief_walk_in_closet',   label: 'Гардеробная',                tag: '#walk_in_closet'      },
    { key: 'brief_bbq',              label: 'Барбекю / зона отдыха',      tag: '#bbq_zone'            },
    { key: 'brief_library',          label: 'Кабинет',                    tag: '#home_library'        },
    { key: 'brief_mud_room',         label: 'Грязный тамбур',             tag: '#mud_room'            },
    { key: 'brief_utility_room',     label: 'Постирочная',                tag: '#utility_laundry'     },
    { key: 'brief_smart_bathroom',   label: 'Умная ванная',               tag: '#smart_bathroom'      },
    { key: 'brief_floor_heating',    label: 'Тёплые полы',                tag: '#floor_heating'       },
    { key: 'brief_hidden_storage',   label: 'Скрытые системы хранения',   tag: '#hidden_storage'      },
  ],

  studio: [
    { key: 'brief_transform_furn',   label: 'Трансформируемая мебель',    tag: '#transform_furniture' },
    { key: 'brief_max_storage',      label: 'Максимальное хранение',      tag: '#max_storage'         },
    { key: 'brief_hidden_storage',   label: 'Скрытые системы хранения',   tag: '#hidden_storage'      },
    { key: 'brief_sleeping_nook',    label: 'Отдельная зона сна',         tag: '#sleeping_nook'       },
    { key: 'brief_open_plan',        label: 'Умное зонирование',          tag: '#smart_zoning'        },
    { key: 'brief_home_cinema',      label: 'Мини-кинозона',              tag: '#home_cinema'         },
    { key: 'brief_work_from_home',   label: 'Рабочее место',              tag: '#work_nook'           },
    { key: 'brief_fold_bed',         label: 'Откидная кровать (Murphy)',  tag: '#murphy_bed'          },
    { key: 'brief_floor_heating',    label: 'Тёплые полы',                tag: '#floor_heating'       },
    { key: 'brief_smart_bathroom',   label: 'Умная ванная',               tag: '#smart_bathroom'      },
    { key: 'brief_kitchen_island',   label: 'Кухонный остров',            tag: '#kitchen_island'      },
  ],

  office: [
    { key: 'brief_meeting_rooms',    label: 'Переговорные',               tag: '#meeting_rooms'       },
    { key: 'brief_phone_booths',     label: 'Тихие кабины (phone booth)', tag: '#phone_booths'        },
    { key: 'brief_reception',        label: 'Зона ресепшн',               tag: '#reception'           },
    { key: 'brief_open_space',       label: 'Open space',                 tag: '#open_space'          },
    { key: 'brief_quiet_offices',    label: 'Тихие кабинеты',             tag: '#quiet_offices'       },
    { key: 'brief_kitchen_area',     label: 'Кухня / обед-зона',          tag: '#kitchen_area'        },
    { key: 'brief_server_room',      label: 'Серверная',                  tag: '#server_room'         },
    { key: 'brief_rest_area',        label: 'Зона отдыха / nap room',     tag: '#rest_area'           },
    { key: 'brief_acoustics',        label: 'Акустика',                   tag: '#acoustics'           },
    { key: 'brief_biophilic_office', label: 'Биофильный офис / растения', tag: '#biophilic_office'    },
    { key: 'brief_branding',         label: 'Фирменный стиль в дизайне',  tag: '#branded_interior'    },
    { key: 'brief_client_wc',        label: 'Санузел для клиентов',       tag: '#client_wc'           },
    { key: 'brief_security',         label: 'Контроль доступа',           tag: '#access_control'      },
    { key: 'brief_mothers_room',     label: 'Комната матери/ребёнка',     tag: '#mothers_room'        },
    { key: 'brief_shower_office',    label: 'Душ для сотрудников',        tag: '#staff_shower'        },
    { key: 'brief_activity_zones',   label: 'Activity-based рабочие места',tag: '#activity_based'     },
    { key: 'brief_lounge',           label: 'Лаунж / informal zones',     tag: '#lounge_area'         },
    { key: 'brief_ergonomics',       label: 'Эргономика рабочих мест',    tag: '#ergonomic_design'    },
  ],

  commercial: [
    { key: 'brief_retail_floor',     label: 'Торговый зал',               tag: '#retail_floor'        },
    { key: 'brief_showcase',         label: 'Витрина / экспозиция',       tag: '#showcase'            },
    { key: 'brief_storage_room',     label: 'Склад / подсобка',           tag: '#storage_back'        },
    { key: 'brief_checkout',         label: 'Касса / ресепшн',            tag: '#checkout_desk'       },
    { key: 'brief_client_wc',        label: 'Санузел для клиентов',       tag: '#client_wc'           },
    { key: 'brief_branding',         label: 'Фирменный стиль',            tag: '#branded_interior'    },
    { key: 'brief_security',         label: 'Видеонаблюдение',            tag: '#cctv'                },
    { key: 'brief_acoustics',        label: 'Акустика',                   tag: '#acoustics'           },
    { key: 'brief_lounge',           label: 'Зона ожидания',              tag: '#lounge_area'         },
    { key: 'brief_kids_corner',      label: 'Детский уголок',             tag: '#kids_corner'         },
    { key: 'brief_photo_zone',       label: 'Фотозона / инсталляция',     tag: '#photo_zone'          },
    { key: 'brief_fitting_room',     label: 'Примерочные',                tag: '#fitting_rooms'       },
    { key: 'brief_staff_area',       label: 'Бэк-офис персонала',         tag: '#staff_area'          },
    { key: 'brief_charging_stations',label: 'Зарядки для гаджетов',       tag: '#charging_stations'   },
    { key: 'brief_digital_signage',  label: 'Digital-вывески / экраны',   tag: '#digital_signage'     },
  ],
}

export const OBJECT_TYPE_LABELS: Record<string, string> = {
  apartment:  'квартира',
  penthouse:  'пентхаус',
  house:      'частный дом',
  townhouse:  'таунхаус',
  studio:     'студия',
  office:     'офис',
  commercial: 'коммерческое',
}
