import { defineVuetifyConfiguration } from 'vuetify-nuxt-module/custom-configuration'

export default defineVuetifyConfiguration({
  theme: {
    defaultTheme: 'messengerLight',
    themes: {
      messengerLight: {
        dark: false,
        colors: {
          primary: '#6750A4',
          'on-primary': '#FFFFFF',
          'primary-container': '#EADDFF',
          'on-primary-container': '#21005D',
          secondary: '#625B71',
          'on-secondary': '#FFFFFF',
          'secondary-container': '#E8DEF8',
          'on-secondary-container': '#1D192B',
          tertiary: '#7D5260',
          'on-tertiary': '#FFFFFF',
          'tertiary-container': '#FFD8E4',
          'on-tertiary-container': '#31111D',
          error: '#B3261E',
          'on-error': '#FFFFFF',
          'error-container': '#F9DEDC',
          'on-error-container': '#410E0B',
          background: '#FEF7FF',
          'on-background': '#1C1B1F',
          surface: '#FEF7FF',
          'on-surface': '#1C1B1F',
          'surface-variant': '#E7E0EC',
          'on-surface-variant': '#49454F',
          outline: '#79747E',
          'outline-variant': '#CAC4D0',
          scrim: '#000000',
          'inverse-surface': '#313033',
          'inverse-on-surface': '#F4EFF4',
          'inverse-primary': '#D0BCFF',
          'surface-container-lowest': '#FFFFFF',
          'surface-container-low': '#F7F2FA',
          'surface-container': '#F3EDF7',
          'surface-container-high': '#ECE6F0',
          'surface-container-highest': '#E6E0E9',
          success: '#386A20',
          warning: '#7C5800',
        },
      },
      messengerDark: {
        dark: true,
        colors: {
          primary: '#D0BCFF',
          'on-primary': '#381E72',
          'primary-container': '#4F378B',
          'on-primary-container': '#EADDFF',
          secondary: '#CCC2DC',
          'on-secondary': '#332D41',
          'secondary-container': '#4A4458',
          'on-secondary-container': '#E8DEF8',
          tertiary: '#EFB8C8',
          'on-tertiary': '#492532',
          'tertiary-container': '#633B48',
          'on-tertiary-container': '#FFD8E4',
          error: '#F2B8B5',
          'on-error': '#601410',
          'error-container': '#8C1D18',
          'on-error-container': '#F9DEDC',
          background: '#141218',
          'on-background': '#E6E1E5',
          surface: '#141218',
          'on-surface': '#E6E1E5',
          'surface-variant': '#49454F',
          'on-surface-variant': '#CAC4D0',
          outline: '#938F99',
          'outline-variant': '#49454F',
          scrim: '#000000',
          'inverse-surface': '#E6E1E5',
          'inverse-on-surface': '#313033',
          'inverse-primary': '#6750A4',
          'surface-container-lowest': '#0F0D13',
          'surface-container-low': '#1D1B20',
          'surface-container': '#211F26',
          'surface-container-high': '#2B2930',
          'surface-container-highest': '#36343B',
          success: '#7EDB5E',
          warning: '#FFBA2C',
        },
      },
    },
  },
  icons: {
    defaultSet: 'mdi',
    sets: ['mdi'],
  },
  defaults: {
    VCard: {
      rounded: 'lg',
      elevation: 0,
    },
    VTextField: {
      variant: 'outlined',
      density: 'comfortable',
      color: 'primary',
      hideDetails: 'auto',
    },
    VBtn: {
      rounded: 'xl',
      variant: 'text',
    },
    VAlert: {
      variant: 'tonal',
      density: 'comfortable',
    },
  },
})