import { z } from 'zod'

export const ClientProfileSchema = z.object({
  // personal
  fio: z.string().optional(),
  birthday: z.string().optional(),
  age: z.string().optional(),
  familyStatus: z.string().optional(),
  children: z.string().optional(),
  pets: z.string().optional(),
  photo: z.string().optional(),
  // contacts
  phone: z.string().optional(),
  phoneExtra: z.string().optional(),
  email: z.string().optional(),
  messenger: z.string().optional(),
  messengerNick: z.string().optional(),
  preferredContact: z.string().optional(),
  address: z.string().optional(),
  // object
  objectAddress: z.string().optional(),
  objectType: z.string().optional(),
  objectTypeCode: z.string().optional(),
  objectCondition: z.string().optional(),
  objectArea: z.string().optional(),
  roomCount: z.string().optional(),
  floor: z.string().optional(),
  ceilingHeight: z.string().optional(),
  hasBalcony: z.string().optional(),
  parking: z.string().optional(),
  // project
  budget: z.string().optional(),
  budgetIncluded: z.string().optional(),
  deadline: z.string().optional(),
  paymentMethod: z.string().optional(),
  referralSource: z.string().optional(),
  previousExperience: z.string().optional(),
  // lifestyle
  lifestyle: z.string().optional(),
  hobbies: z.string().optional(),
  stylePreferences: z.string().optional(),
  colorPreferences: z.string().optional(),
  allergies: z.string().optional(),
  priorities: z.string().optional(),
  dislikes: z.string().optional(),
  notes: z.string().optional(),
  // catalog selects
  clientType: z.string().optional(),
  objectTypeCode2: z.string().optional(),
  projectPriority: z.string().optional(),
  roadmapComplexity: z.string().optional(),
  paymentType: z.string().optional(),
  contractType: z.string().optional(),
  roadmapStageType: z.string().optional(),
  // chips (multi-select arrays)
  designerServiceTypes: z.array(z.string()).optional(),
  contractorWorkTypes: z.array(z.string()).optional(),
  // ── Phase 0: Smart Briefing ──────────────────────────────────
  brief_smart_home:     z.boolean().optional(),
  brief_kids_room:      z.boolean().optional(),
  brief_work_from_home: z.boolean().optional(),
  brief_soundproofing:  z.boolean().optional(),
  brief_pets:           z.boolean().optional(),
  brief_storage:        z.boolean().optional(),
  brief_home_gym:       z.boolean().optional(),
  brief_home_cinema:    z.boolean().optional(),
  brief_chef_kitchen:   z.boolean().optional(),
  brief_sauna:          z.boolean().optional(),
  brief_gallery:        z.boolean().optional(),
  brief_wine_cellar:    z.boolean().optional(),
  brief_adults_count:   z.string().optional(),
  brief_kids_ages:      z.string().optional(),
  brief_ergonomics:     z.string().optional(),
  brief_handed:         z.string().optional(),
  brief_pets_desc:      z.string().optional(),
  brief_pets_zone_detail: z.string().optional(),
  brief_remote_work:    z.string().optional(),
  brief_guests_freq:    z.string().optional(),
  brief_hobbies:        z.string().optional(),
  brief_morning_routine: z.string().optional(),
  brief_evening_routine: z.string().optional(),
  brief_cooking_role:   z.string().optional(),
  brief_bedroom_needs:  z.string().optional(),
  brief_acoustic_zones: z.string().optional(),
  brief_flex_zones:     z.string().optional(),
  brief_future_changes: z.string().optional(),
  brief_style_prefer:   z.string().optional(),
  brief_color_mood:     z.string().optional(),
  brief_color_palette:  z.string().optional(),
  brief_like_refs:      z.string().optional(),
  brief_dislike_refs:   z.string().optional(),
  brief_material_prefs: z.string().optional(),
  brief_textures:       z.string().optional(),
  brief_prints:         z.string().optional(),
  brief_art:            z.string().optional(),
  brief_home_mood:      z.string().optional(),
  brief_return_emotion: z.string().optional(),
  brief_space_image:    z.string().optional(),
  brief_kitchen_intensity: z.string().optional(),
  brief_kitchen_surfaces: z.string().optional(),
  brief_kitchen_cabinets: z.string().optional(),
  brief_kitchen_hardware: z.string().optional(),
  brief_kitchen_cooktop: z.string().optional(),
  brief_kitchen_oven:   z.string().optional(),
  brief_kitchen_appliances: z.string().optional(),
  brief_kitchen_sink:   z.string().optional(),
  brief_sport_zone:     z.string().optional(),
  brief_sport_storage:  z.string().optional(),
  brief_sport_tech:     z.string().optional(),
  brief_storage_volume: z.string().optional(),
  brief_storage_hidden: z.string().optional(),
  brief_utility_zone:   z.string().optional(),
  brief_light_modes:    z.string().optional(),
  brief_light_dimming:  z.string().optional(),
  brief_light_automation: z.string().optional(),
  brief_smart_control:  z.string().optional(),
  brief_acoustics_type: z.string().optional(),
  brief_tech_equipment: z.string().optional(),
  brief_allergies:      z.string().optional(),
  brief_deadlines_hard: z.string().optional(),
  brief_budget_limits:  z.string().optional(),
  brief_budget_priorities: z.string().optional(),
  brief_special_notes:  z.string().optional(),
  brief_completed:      z.boolean().optional(),
  // ── Phase 0: Site Survey ─────────────────────────────────────
  survey_status:        z.string().optional(),
  survey_date:          z.string().optional(),
  survey_engineer:      z.string().optional(),
  survey_address:       z.string().optional(),
  survey_area:          z.string().optional(),
  survey_ceiling:       z.string().optional(),
  survey_mep_notes:     z.string().optional(),
  survey_issues:        z.string().optional(),
  survey_recommendations: z.string().optional(),
  survey_notes:         z.string().optional(),
  survey_files:         z.array(z.any()).optional(),
  mep_ventilation:      z.boolean().optional(),
  mep_plumbing:         z.boolean().optional(),
  mep_electrical:       z.boolean().optional(),
  mep_heating:          z.boolean().optional(),
  mep_gas:              z.boolean().optional(),
  mep_smart:            z.boolean().optional(),
  mep_balcony:          z.boolean().optional(),
  mep_structural:       z.boolean().optional(),
  // ── Phase 0: ToR & Contract ──────────────────────────────────
  contract_number:      z.string().optional(),
  contract_date:        z.string().optional(),
  contract_status:      z.string().optional(),
  contract_parties:     z.string().optional(),
  contract_file:        z.string().optional(),
  contract_filename:    z.string().optional(),
  contract_notes:       z.string().optional(),
  invoice_amount:       z.string().optional(),
  invoice_advance_pct:  z.string().optional(),
  invoice_date:         z.string().optional(),
  payment_status:       z.string().optional(),
  invoice_file:         z.string().optional(),
  invoice_filename:     z.string().optional(),
  invoice_payment_details: z.string().optional(),
  tor_scope:            z.string().optional(),
  tor_exclusions:       z.string().optional(),
  tor_timeline:         z.string().optional(),
  tor_deliverables:     z.string().optional(),
}).passthrough()
export type ClientProfile = z.infer<typeof ClientProfileSchema>

export const ProjectSchema = z.object({
  id: z.number(),
  slug: z.string().min(1),
  title: z.string().min(1),
  pages: z.array(z.string()),
  profile: ClientProfileSchema,
})
export const CreateProjectSchema = z.object({
  slug: z.string().min(1).regex(/^[a-z0-9_-]+$/),
  title: z.string().min(1),
  roadmapTemplateKey: z.string().optional(),
})
export const UpdateProjectSchema = CreateProjectSchema.partial().extend({
  status: z.string().optional(),
  pages: z.array(z.string()).optional(),
  profile: ClientProfileSchema.optional(),
})
export type Project = z.infer<typeof ProjectSchema>
export type CreateProject = z.infer<typeof CreateProjectSchema>
export type UpdateProject = z.infer<typeof UpdateProjectSchema>
