import { CLIENT_TYPES, OBJECT_TYPES, ROADMAP_COMPLEXITY_TYPES, ROADMAP_STAGE_TYPES } from './catalogs'

type ClientType = typeof CLIENT_TYPES[number]
type ObjectType = typeof OBJECT_TYPES[number]
type ComplexityType = typeof ROADMAP_COMPLEXITY_TYPES[number]
type StageKey = typeof ROADMAP_STAGE_TYPES[number]

export interface RoadmapTemplateStage {
  stageKey: StageKey
  title: string
  description?: string
  notes?: string
}

export interface RoadmapTemplate {
  key: string
  title: string
  objectType: ObjectType
  clientType: ClientType
  complexity: ComplexityType
  description: string
  stages: RoadmapTemplateStage[]
}

export const ROADMAP_TEMPLATES: RoadmapTemplate[] = [
  {
    key: 'apartment_physical_basic',
    title: 'Квартира · Физлицо · Базовый',
    objectType: 'apartment',
    clientType: 'physical_person',
    complexity: 'basic',
    description: 'Быстрый сценарий для типовой квартиры без сложных инженерных решений.',
    stages: [
      { stageKey: 'brief', title: 'Бриф и обмер', description: 'Сбор требований, обмер и фотофиксация.' },
      { stageKey: 'concept', title: 'Концепция', description: 'Стилистика, коллажи, базовая цветовая палитра.' },
      { stageKey: 'planning', title: 'Планировочное решение', description: '2–3 варианта расстановки мебели.' },
      { stageKey: 'procurement', title: 'Подбор материалов', description: 'Базовые ведомости по отделке и мебели.' },
      { stageKey: 'implementation', title: 'Реализация', description: 'Контроль соответствия проекту.' },
      { stageKey: 'handover', title: 'Сдача', description: 'Итоговая проверка и передача рекомендаций.' },
    ],
  },
  {
    key: 'apartment_family_standard',
    title: 'Квартира · Семья · Стандарт',
    objectType: 'apartment',
    clientType: 'family',
    complexity: 'standard',
    description: 'Сценарий с учётом детской, хранения, безопасных материалов.',
    stages: [
      { stageKey: 'brief', title: 'Семейный бриф', description: 'Сценарии жизни семьи и бытовые привычки.' },
      { stageKey: 'concept', title: 'Концепция и зонирование', description: 'Стили, референсы, приватные/общие зоны.' },
      { stageKey: 'planning', title: 'Планировка', description: 'Эргономика и хранение для семьи.' },
      { stageKey: 'engineering', title: 'Инженерия', description: 'Розетки, световые группы, сантехточки.' },
      { stageKey: 'procurement', title: 'Комплектация', description: 'Подбор мебели, текстиля и безопасных материалов.' },
      { stageKey: 'implementation', title: 'Ремонт', description: 'Авторский контроль ключевых узлов.' },
      { stageKey: 'handover', title: 'Финальная сдача', description: 'Проверка, рекомендации по эксплуатации.' },
    ],
  },
  {
    key: 'house_physical_advanced',
    title: 'Дом · Физлицо · Повышенная сложность',
    objectType: 'house',
    clientType: 'physical_person',
    complexity: 'advanced',
    description: 'Частный дом с инженерными системами и расширенной спецификацией.',
    stages: [
      { stageKey: 'brief', title: 'Бриф и обследование дома' },
      { stageKey: 'concept', title: 'Общая концепция по этажам' },
      { stageKey: 'planning', title: 'Планировочные решения и сценарии перемещения' },
      { stageKey: 'engineering', title: 'Инженерные разделы', description: 'ОВиК, электрика, слаботочка.' },
      { stageKey: 'procurement', title: 'Комплектация и смета' },
      { stageKey: 'implementation', title: 'Реализация работ' },
      { stageKey: 'supervision', title: 'Авторский надзор', description: 'Регулярные выезды и акты замечаний.' },
      { stageKey: 'handover', title: 'Сдача дома' },
    ],
  },
  {
    key: 'office_legal_standard',
    title: 'Офис · Юрлицо · Стандарт',
    objectType: 'office',
    clientType: 'legal_entity',
    complexity: 'standard',
    description: 'Офисный проект с фокусом на рабочие процессы и корпоративный стиль.',
    stages: [
      { stageKey: 'brief', title: 'Бриф с бизнес-целями' },
      { stageKey: 'concept', title: 'Концепция пространства бренда' },
      { stageKey: 'planning', title: 'Планировка рабочих зон' },
      { stageKey: 'engineering', title: 'ТЗ на инженерные разделы' },
      { stageKey: 'procurement', title: 'Смета и тендер поставщиков' },
      { stageKey: 'implementation', title: 'Строительно-монтажные работы' },
      { stageKey: 'handover', title: 'Ввод в эксплуатацию' },
    ],
  },
  {
    key: 'retail_legal_fast',
    title: 'Ритейл · Юрлицо · Базовый/быстрый',
    objectType: 'retail',
    clientType: 'legal_entity',
    complexity: 'basic',
    description: 'Сценарий для быстрого запуска торговой точки.',
    stages: [
      { stageKey: 'brief', title: 'Коммерческий бриф' },
      { stageKey: 'concept', title: 'Концепция торгового зала' },
      { stageKey: 'planning', title: 'План оборудования и потоков' },
      { stageKey: 'procurement', title: 'Оперативная комплектация' },
      { stageKey: 'implementation', title: 'Монтаж и отделка' },
      { stageKey: 'handover', title: 'Подготовка к открытию' },
    ],
  },
  {
    key: 'horeca_investor_premium',
    title: 'HoReCa · Инвестор · Премиум',
    objectType: 'horeca',
    clientType: 'investor',
    complexity: 'premium',
    description: 'Сложный проект с высокой детализацией дизайна и авторским надзором.',
    stages: [
      { stageKey: 'brief', title: 'Бриф и бизнес-модель' },
      { stageKey: 'concept', title: 'Концепция бренда и атмосферы' },
      { stageKey: 'planning', title: 'Функциональное зонирование зала/кухни' },
      { stageKey: 'engineering', title: 'Инженерия и требования эксплуатации' },
      { stageKey: 'procurement', title: 'Премиальная комплектация и кастом' },
      { stageKey: 'implementation', title: 'Реализация интерьера' },
      { stageKey: 'supervision', title: 'Интенсивный авторский надзор' },
      { stageKey: 'handover', title: 'Сдача и pre-open проверка' },
    ],
  },
  {
    key: 'apartment_legal_standard',
    title: 'Квартира (под аренду) · Юрлицо · Стандарт',
    objectType: 'apartment',
    clientType: 'legal_entity',
    complexity: 'standard',
    description: 'Инвестиционный сценарий: баланс стоимости и срока, подготовка к сдаче в аренду.',
    stages: [
      { stageKey: 'brief', title: 'Бриф инвестиционных целей' },
      { stageKey: 'concept', title: 'Концепция ликвидного интерьера' },
      { stageKey: 'planning', title: 'Планировка и хранение' },
      { stageKey: 'engineering', title: 'Инженерия под эксплуатацию' },
      { stageKey: 'procurement', title: 'Комплектация из складских позиций' },
      { stageKey: 'implementation', title: 'Ремонтные работы' },
      { stageKey: 'handover', title: 'Сдача объекта и check-list' },
    ],
  },
  {
    key: 'apartment_investor_advanced',
    title: 'Квартира · Инвестор · Повышенная сложность',
    objectType: 'apartment',
    clientType: 'investor',
    complexity: 'advanced',
    description: 'Сценарий с повышенной детализацией, кастомными решениями и контролем бюджета.',
    stages: [
      { stageKey: 'brief', title: 'Бриф, KPI и бюджетные рамки' },
      { stageKey: 'concept', title: 'Концепция и конкурентный анализ' },
      { stageKey: 'planning', title: 'Планировочное решение и мебельные узлы' },
      { stageKey: 'engineering', title: 'Инженерные разделы' },
      { stageKey: 'procurement', title: 'Тендер и договоры поставки' },
      { stageKey: 'implementation', title: 'Реализация и контроль качества' },
      { stageKey: 'supervision', title: 'Авторский надзор' },
      { stageKey: 'handover', title: 'Финальная приемка' },
    ],
  },
  {
    key: 'house_family_standard',
    title: 'Дом · Семья · Стандарт',
    objectType: 'house',
    clientType: 'family',
    complexity: 'standard',
    description: 'Семейный дом с акцентом на функциональность, детские зоны и безопасные материалы.',
    stages: [
      { stageKey: 'brief', title: 'Семейный бриф и сценарии по этажам' },
      { stageKey: 'concept', title: 'Концепция и материалы' },
      { stageKey: 'planning', title: 'Планировка комнат и систем хранения' },
      { stageKey: 'engineering', title: 'Инженерные разделы (свет, водоснабжение)' },
      { stageKey: 'procurement', title: 'Комплектация материалов и мебели' },
      { stageKey: 'implementation', title: 'Строительно-отделочные работы' },
      { stageKey: 'handover', title: 'Сдача и инструкции по эксплуатации' },
    ],
  },
  {
    key: 'house_legal_premium',
    title: 'Дом (резиденция) · Юрлицо · Премиум',
    objectType: 'house',
    clientType: 'legal_entity',
    complexity: 'premium',
    description: 'Премиальный сценарий с custom-производствами, расширенным надзором и актированием.',
    stages: [
      { stageKey: 'brief', title: 'Бриф, бренд-позиционирование резиденции' },
      { stageKey: 'concept', title: 'Премиальная концепция и moodboard' },
      { stageKey: 'planning', title: 'Планировка и сценарии сервисных зон' },
      { stageKey: 'engineering', title: 'Инженерия high-end уровня' },
      { stageKey: 'procurement', title: 'Комплектация и custom-заказы' },
      { stageKey: 'implementation', title: 'Реализация и поэтапная приемка' },
      { stageKey: 'supervision', title: 'Интенсивный авторский надзор' },
      { stageKey: 'handover', title: 'Сдача с исполнительной документацией' },
    ],
  },
  {
    key: 'office_physical_basic',
    title: 'Офис (малый) · Физлицо · Базовый',
    objectType: 'office',
    clientType: 'physical_person',
    complexity: 'basic',
    description: 'Быстрый запуск небольшого офиса или кабинета.',
    stages: [
      { stageKey: 'brief', title: 'Бриф и функциональные требования' },
      { stageKey: 'concept', title: 'Базовая стилистика' },
      { stageKey: 'planning', title: 'Расстановка рабочих мест' },
      { stageKey: 'procurement', title: 'Подбор складской мебели' },
      { stageKey: 'implementation', title: 'Монтаж и отделка' },
      { stageKey: 'handover', title: 'Запуск офиса' },
    ],
  },
  {
    key: 'office_developer_advanced',
    title: 'Офис (штаб-квартира) · Девелопер · Повышенная сложность',
    objectType: 'office',
    clientType: 'developer',
    complexity: 'advanced',
    description: 'Сценарий для корпоративного офиса с брендингом, инженерией и staged-сдачей.',
    stages: [
      { stageKey: 'brief', title: 'Бриф и бренд-стратегия офиса' },
      { stageKey: 'concept', title: 'Концепция identity-пространства' },
      { stageKey: 'planning', title: 'Планировка командных/тихих зон' },
      { stageKey: 'engineering', title: 'Инженерные системы и IT-инфраструктура' },
      { stageKey: 'procurement', title: 'Тендер и закупки' },
      { stageKey: 'implementation', title: 'Поэтапная реализация' },
      { stageKey: 'supervision', title: 'Надзор и координация подрядчиков' },
      { stageKey: 'handover', title: 'Сдача и onboarding команды' },
    ],
  },
  {
    key: 'retail_investor_standard',
    title: 'Ритейл · Инвестор · Стандарт',
    objectType: 'retail',
    clientType: 'investor',
    complexity: 'standard',
    description: 'Сценарий для магазина с акцентом на клиентский путь и конверсию.',
    stages: [
      { stageKey: 'brief', title: 'Бриф по ЦА и форматам продаж' },
      { stageKey: 'concept', title: 'Концепция торгового опыта' },
      { stageKey: 'planning', title: 'План оборудования и customer-flow' },
      { stageKey: 'engineering', title: 'Инженерия торгового зала' },
      { stageKey: 'procurement', title: 'Поставка оборудования и POS' },
      { stageKey: 'implementation', title: 'Монтаж и подготовка к открытию' },
      { stageKey: 'handover', title: 'Техническое открытие' },
    ],
  },
  {
    key: 'retail_developer_premium',
    title: 'Ритейл (флагман) · Девелопер · Премиум',
    objectType: 'retail',
    clientType: 'developer',
    complexity: 'premium',
    description: 'Флагманский магазин с custom-элементами и высокой плотностью согласований.',
    stages: [
      { stageKey: 'brief', title: 'Бриф и KPI флагманского формата' },
      { stageKey: 'concept', title: 'Флагманская концепция и прототипирование' },
      { stageKey: 'planning', title: 'Планировка с event-зонами' },
      { stageKey: 'engineering', title: 'Инженерия и медиа-интеграции' },
      { stageKey: 'procurement', title: 'Custom-производства и логистика' },
      { stageKey: 'implementation', title: 'Реализация в сжатые окна работ' },
      { stageKey: 'supervision', title: 'Надзор, quality gates, punch list' },
      { stageKey: 'handover', title: 'Grand opening готовность' },
    ],
  },
  {
    key: 'horeca_legal_standard',
    title: 'HoReCa · Юрлицо · Стандарт',
    objectType: 'horeca',
    clientType: 'legal_entity',
    complexity: 'standard',
    description: 'Стандартный ресторан/кафе: баланс концепции, эргономики и эксплуатационных требований.',
    stages: [
      { stageKey: 'brief', title: 'Бриф формата и кухни' },
      { stageKey: 'concept', title: 'Концепция зала и атмосферы' },
      { stageKey: 'planning', title: 'Планировка гостевых/производственных зон' },
      { stageKey: 'engineering', title: 'Инженерные требования HoReCa' },
      { stageKey: 'procurement', title: 'Комплектация мебели и оборудования' },
      { stageKey: 'implementation', title: 'Реализация и отделка' },
      { stageKey: 'handover', title: 'Pre-open проверка' },
    ],
  },
  {
    key: 'public_legal_basic',
    title: 'Общественное пространство · Юрлицо · Базовый',
    objectType: 'public_space',
    clientType: 'legal_entity',
    complexity: 'basic',
    description: 'Типовой сценарий благоустройства внутреннего общественного пространства.',
    stages: [
      { stageKey: 'brief', title: 'Бриф и требования эксплуатации' },
      { stageKey: 'concept', title: 'Базовая концепция пространства' },
      { stageKey: 'planning', title: 'Планировка и потоки' },
      { stageKey: 'procurement', title: 'Комплектация типовыми решениями' },
      { stageKey: 'implementation', title: 'Монтаж и отделка' },
      { stageKey: 'handover', title: 'Сдача и запуск' },
    ],
  },
  {
    key: 'public_developer_advanced',
    title: 'Общественное пространство · Девелопер · Повышенная сложность',
    objectType: 'public_space',
    clientType: 'developer',
    complexity: 'advanced',
    description: 'Сценарий для лобби/общественных зон ЖК или БЦ с высокой проходимостью.',
    stages: [
      { stageKey: 'brief', title: 'Бриф девелопера и эксплуатационные KPI' },
      { stageKey: 'concept', title: 'Концепция общественных зон' },
      { stageKey: 'planning', title: 'Планировка потоков и сервисных точек' },
      { stageKey: 'engineering', title: 'Инженерные и противопожарные решения' },
      { stageKey: 'procurement', title: 'Комплектация устойчивыми материалами' },
      { stageKey: 'implementation', title: 'Реализация под график объекта' },
      { stageKey: 'supervision', title: 'Надзор и QA/QC' },
      { stageKey: 'handover', title: 'Сдача в управляющую компанию' },
    ],
  },
  {
    key: 'office_investor_premium',
    title: 'Офис (представительский) · Инвестор · Премиум',
    objectType: 'office',
    clientType: 'investor',
    complexity: 'premium',
    description: 'Представительский офис с премиальными зонами переговоров и custom-деталями.',
    stages: [
      { stageKey: 'brief', title: 'Стратегический бриф и протоколы бренда' },
      { stageKey: 'concept', title: 'Премиальная концепция интерьера' },
      { stageKey: 'planning', title: 'Планировка представительских/рабочих зон' },
      { stageKey: 'engineering', title: 'Инженерия и мультимедиа' },
      { stageKey: 'procurement', title: 'Комплектация и custom-производство' },
      { stageKey: 'implementation', title: 'Реализация и поузловая приемка' },
      { stageKey: 'supervision', title: 'Авторский надзор + weekly отчеты' },
      { stageKey: 'handover', title: 'Сдача и executive walkthrough' },
    ],
  },
  {
    key: 'house_investor_standard',
    title: 'Дом (аренда/продажа) · Инвестор · Стандарт',
    objectType: 'house',
    clientType: 'investor',
    complexity: 'standard',
    description: 'Сценарий для подготовки дома под продажу или долгосрочную аренду.',
    stages: [
      { stageKey: 'brief', title: 'Бриф рыночной стратегии' },
      { stageKey: 'concept', title: 'Концепция ликвидного продукта' },
      { stageKey: 'planning', title: 'Планировка и staging-подготовка' },
      { stageKey: 'engineering', title: 'Инженерная ревизия' },
      { stageKey: 'procurement', title: 'Комплектация под бюджет и сроки' },
      { stageKey: 'implementation', title: 'Реализация и подготовка к показам' },
      { stageKey: 'handover', title: 'Сдача и маркетинг-пакет' },
    ],
  },
  {
    key: 'apartment_developer_premium',
    title: 'Квартира (show-unit) · Девелопер · Премиум',
    objectType: 'apartment',
    clientType: 'developer',
    complexity: 'premium',
    description: 'Сценарий витринной квартиры для продаж в девелоперском проекте.',
    stages: [
      { stageKey: 'brief', title: 'Бриф продуктовой линейки ЖК' },
      { stageKey: 'concept', title: 'Show-unit концепция и storytelling' },
      { stageKey: 'planning', title: 'Планировка под демонстрационные сценарии' },
      { stageKey: 'engineering', title: 'Инженерия и медиа-сценарии' },
      { stageKey: 'procurement', title: 'Комплектация и staging-пакет' },
      { stageKey: 'implementation', title: 'Реализация show-unit' },
      { stageKey: 'supervision', title: 'Контроль отделки и декорирования' },
      { stageKey: 'handover', title: 'Сдача отделу продаж' },
    ],
  },
  {
    key: 'retail_physical_basic',
    title: 'Ритейл (остров) · Физлицо · Базовый',
    objectType: 'retail',
    clientType: 'physical_person',
    complexity: 'basic',
    description: 'Мини-сценарий для островного/небольшого ритейла с быстрым запуском.',
    stages: [
      { stageKey: 'brief', title: 'Бриф формата и бюджета' },
      { stageKey: 'concept', title: 'Базовая концепция точки' },
      { stageKey: 'planning', title: 'План оборудования и выкладки' },
      { stageKey: 'procurement', title: 'Оперативная закупка' },
      { stageKey: 'implementation', title: 'Сборка и монтаж' },
      { stageKey: 'handover', title: 'Открытие точки' },
    ],
  },
  {
    key: 'horeca_family_standard',
    title: 'HoReCa (семейное кафе) · Семья · Стандарт',
    objectType: 'horeca',
    clientType: 'family',
    complexity: 'standard',
    description: 'Сценарий семейного кафе с безопасными материалами и детской зоной.',
    stages: [
      { stageKey: 'brief', title: 'Бриф формата и гостевых сценариев' },
      { stageKey: 'concept', title: 'Концепция атмосферы и бренда' },
      { stageKey: 'planning', title: 'Планировка зала/барной/детской зон' },
      { stageKey: 'engineering', title: 'Инженерные требования HoReCa' },
      { stageKey: 'procurement', title: 'Комплектация мебели и оборудования' },
      { stageKey: 'implementation', title: 'Реализация и отделка' },
      { stageKey: 'handover', title: 'Сдача перед открытием' },
    ],
  },
  {
    key: 'public_investor_standard',
    title: 'Общественное пространство · Инвестор · Стандарт',
    objectType: 'public_space',
    clientType: 'investor',
    complexity: 'standard',
    description: 'Сценарий общественной зоны в составе инвестиционного проекта.',
    stages: [
      { stageKey: 'brief', title: 'Бриф доходной модели и аудитории' },
      { stageKey: 'concept', title: 'Концепция опыта посетителя' },
      { stageKey: 'planning', title: 'Планировка сервисных и транзитных зон' },
      { stageKey: 'engineering', title: 'Инженерные требования и эксплуатация' },
      { stageKey: 'procurement', title: 'Комплектация и календарь поставок' },
      { stageKey: 'implementation', title: 'Реализация и пусконаладка' },
      { stageKey: 'handover', title: 'Сдача и запуск' },
    ],
  },
]
