/**
 * Tenders domain types used by `server/modules/tenders/` and any
 * frontend slice that consumes the tenders API.
 *
 * Pure shared layer — no drizzle/h3/db driver imports.
 */

import type { SourceId, UnifiedTender } from './tenders-ingest'

/**
 * Canonical lifecycle status of a tender row from the project owner's
 * perspective. Initial value is always 'new'. Transitions are linear
 * and project-scoped (a tender belongs to one project at a time).
 */
export type TenderStatus =
  | 'new'
  | 'reviewed'
  | 'preparing'
  | 'submitted'
  | 'won'
  | 'lost'
  | 'skipped'

export const TENDER_STATUSES: readonly TenderStatus[] = [
  'new',
  'reviewed',
  'preparing',
  'submitted',
  'won',
  'lost',
  'skipped',
] as const

/**
 * Tender row — DB-aligned shape returned by the search endpoint. Mirrors
 * the columns in `tenders` (server/db/schema/tenders.ts) plus a couple
 * of derived fields. Kept handwritten (not `$inferSelect`) so the
 * shared layer does not import from `server/db`.
 */
export interface TenderRow {
  id: string
  sourceId: SourceId
  externalGuid: string
  law: '44-fz' | '223-fz' | 'imushestvo' | 'other'
  procedureType: string
  publishedAt: string
  customer: {
    inn: string
    kpp?: string | null
    name: string
    region: string
  }
  title: string
  description: string | null
  okpd2: string[]
  startPrice: string | null
  currency: 'RUB'
  deadlineAt: string | null
  applicationStart: string | null
  applicationEnd: string | null
  documentsUrls: string[]
  status: TenderStatus
  relevanceScore: number | null
  marginScore: number | null
  createdAt: string
  updatedAt: string
  version: number
}

/**
 * Single item in the ingest payload. Same shape as `UnifiedTender` —
 * re-exported here to keep one canonical name for the API contract.
 */
export type TenderIngestItem = UnifiedTender

/**
 * Bulk ingest envelope. The service-internal client posts batches of
 * ~50 items at a time; the publisher computes `idempotencyKey` from
 * `(sourceId, batch hash)` so a re-run with the same content is a no-op.
 */
export interface TenderIngestRequest {
  sourceId: SourceId
  /** Generated by ingest-service: `ingest-<sourceId>-<sha256(payload).slice(0,16)>`. */
  idempotencyKey: string
  items: TenderIngestItem[]
}

export interface TenderIngestResponse {
  accepted: number
  inserted: number
  updated: number
  skipped: number
}

/**
 * Cursor-paginated search response. Consumers always pass the previous
 * `nextCursor` back; offset pagination is forbidden by ADR-001.
 */
export interface TenderSearchQuery {
  cursor?: string
  limit?: number
  okpd2?: string[]
  regions?: string[]
  status?: TenderStatus
  sourceId?: SourceId
}

export interface TenderSearchResult {
  items: TenderRow[]
  nextCursor: string | null
}
