import type { DesignPreset } from './useDesignSystem.core'

const SYSTEM_UI_FONT_STACK = '"SF Pro Text", "SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI Variable", "Segoe UI", system-ui, sans-serif'
const M3_FONT_STACK = '"SF Pro Text", -apple-system, BlinkMacSystemFont, "Segoe UI Variable", "Segoe UI", system-ui, sans-serif'
const NEO_GROTESK_FONT_STACK = '"Avenir Next", "Helvetica Neue", "Segoe UI Variable", "Segoe UI", Arial, sans-serif'
const SHARP_SANS_FONT_STACK = '"SF Pro Display", "Helvetica Neue", "Segoe UI Variable", "Segoe UI", Arial, sans-serif'
const HUMANIST_SANS_FONT_STACK = '"Avenir Next", "Trebuchet MS", "Segoe UI", Arial, sans-serif'
const DISPLAY_SANS_FONT_STACK = '"Avenir Next", "Helvetica Neue", "Segoe UI", Arial, sans-serif'
const WIDE_SANS_FONT_STACK = '"Arial Narrow", "Avenir Next Condensed", "Helvetica Neue", "Segoe UI", Arial, sans-serif'
const UI_SANS_FONT_STACK = '"Segoe UI Variable", -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif'
const MONO_FONT_STACK = '"JetBrains Mono", "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace'
const EDITORIAL_SERIF_FONT_STACK = 'Iowan Old Style, Georgia, "Times New Roman", serif'
const JAPANESE_UI_FONT_STACK = '"Hiragino Sans", "Yu Gothic UI", "Yu Gothic", Meiryo, "MS PGothic", system-ui, sans-serif'
const BRUTAL_DISPLAY_FONT_STACK = '"Arial Black", "Arial Narrow", "Helvetica Neue", Arial, sans-serif'

export const DESIGN_PRESETS: DesignPreset[] = [
  {
    id: 'minimal',
    name: 'Минимализм',
    description: 'Чистый и лаконичный — как Linear',
    icon: '◻',
    tokens: {
      btnRadius: 4, btnStyle: 'outline', btnTransform: 'none', btnWeight: 400,
      btnPaddingH: 0, btnPaddingV: 0,
      btnHoverAnim: 'none', cardHoverAnim: 'dim',
      fontWeight: 400, headingWeight: 500, letterSpacing: 0.02, lineHeight: 1.55, typeScale: 1.15,
      glassBlur: 12, glassOpacity: 0.35, glassBorderOpacity: 0.05, glassSaturation: 120,
      shadowOffsetY: 4, shadowBlurRadius: 16, shadowOpacity: 0.04,
      cardRadius: 8, inputRadius: 4, chipRadius: 4, modalRadius: 10,
      animDuration: 140, animEasing: 'ease', borderWidth: 1, gridGap: 14,
      accentHue: 220, accentSaturation: 12, accentLightness: 48,
      darkElevation: 4, darkSaturation: 40,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.08, inputPaddingH: 10, inputPaddingV: 7, inputFontSize: 0,
      chipBgOpacity: 0.05, chipBorderOpacity: 0.06, chipPaddingH: 8, chipPaddingV: 2,
      navItemRadius: 6, navItemPaddingH: 10, navItemPaddingV: 5,
      statusBgOpacity: 0.07, statusPillRadius: 4,
      modalOverlayOpacity: 0.30, dropdownBlur: 12,
      scrollbarWidth: 3, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.03, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.06,
      badgeBgOpacity: 0.10, badgeRadius: 4,
      archDensity: 'normal', archHeadingTracking: 2, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'flat',
    },
  },
  {
    id: 'soft',
    name: 'Мягкость',
    description: 'Округлый и мягкий — как Notion',
    icon: '◉',
    tokens: {
      btnRadius: 999, btnStyle: 'soft', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      btnHoverAnim: 'lift', cardHoverAnim: 'lift',
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.02, lineHeight: 1.6, typeScale: 1.2,
      glassBlur: 24, glassOpacity: 0.55, glassBorderOpacity: 0.06, glassSaturation: 160,
      shadowOffsetY: 10, shadowBlurRadius: 32, shadowOpacity: 0.07,
      cardRadius: 20, inputRadius: 12, chipRadius: 999, modalRadius: 22,
      animDuration: 220, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 0, gridGap: 18,
      accentHue: 280, accentSaturation: 25, accentLightness: 55,
      darkElevation: 8, darkSaturation: 55,
      inputBgOpacity: 0.06, inputBorderOpacity: 0.00, inputPaddingH: 14, inputPaddingV: 9, inputFontSize: 0,
      chipBgOpacity: 0.08, chipBorderOpacity: 0.00, chipPaddingH: 11, chipPaddingV: 4,
      navItemRadius: 999, navItemPaddingH: 14, navItemPaddingV: 7,
      statusBgOpacity: 0.10, statusPillRadius: 999,
      modalOverlayOpacity: 0.30, dropdownBlur: 20,
      scrollbarWidth: 5, scrollbarOpacity: 0.12,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.05,
      badgeBgOpacity: 0.14, badgeRadius: 999,
      archDensity: 'airy', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'brutalist',
    name: 'Брутализм',
    description: 'Резкий и контрастный — без компромиссов',
    icon: '▬',
    tokens: {
      btnRadius: 0, btnStyle: 'outline', btnTransform: 'uppercase', btnWeight: 700,
      btnPaddingH: 20, btnPaddingV: 10,
      btnHoverAnim: 'fill', cardHoverAnim: 'border',
      fontWeight: 400, headingWeight: 800, letterSpacing: 0.08, lineHeight: 1.35, typeScale: 1.333,
      glassBlur: 0, glassOpacity: 0.92, glassBorderOpacity: 0.2, glassSaturation: 100,
      shadowOffsetY: 4, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0.12,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 60, animEasing: 'linear', borderWidth: 2, gridGap: 12,
      accentHue: 0, accentSaturation: 0, accentLightness: 20,
      darkElevation: 2, darkSaturation: 10,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.20, inputPaddingH: 10, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.20, chipPaddingH: 8, chipPaddingV: 3,
      navItemRadius: 0, navItemPaddingH: 10, navItemPaddingV: 6,
      statusBgOpacity: 0.12, statusPillRadius: 0,
      modalOverlayOpacity: 0.50, dropdownBlur: 0,
      scrollbarWidth: 6, scrollbarOpacity: 0.25,
      tableHeaderOpacity: 0.08, tableRowHoverOpacity: 0.05, tableBorderOpacity: 0.15,
      badgeBgOpacity: 0.15, badgeRadius: 0,
      archDensity: 'dense', archHeadingTracking: -3, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'none', archSectionStyle: 'striped',
    },
  },
  {
    id: 'corporate',
    name: 'Корпоративный',
    description: 'Деловой — как Salesforce / Stripe',
    icon: '▣',
    tokens: {
      btnRadius: 100, btnStyle: 'filled', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.03, lineHeight: 1.5, typeScale: 1.25,
      glassBlur: 14, glassOpacity: 0.62, glassBorderOpacity: 0.09, glassSaturation: 130,
      shadowOffsetY: 6, shadowBlurRadius: 20, shadowOpacity: 0.06,
      cardRadius: 10, inputRadius: 6, chipRadius: 20, modalRadius: 12,
      animDuration: 160, animEasing: 'ease-in-out', borderWidth: 1, gridGap: 16,
      accentHue: 215, accentSaturation: 60, accentLightness: 50,
      darkElevation: 5, darkSaturation: 45,
      inputBgOpacity: 0.05, inputBorderOpacity: 0.10, inputPaddingH: 12, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.06, chipBorderOpacity: 0.08, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 6, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.09, statusPillRadius: 20,
      modalOverlayOpacity: 0.35, dropdownBlur: 14,
      scrollbarWidth: 4, scrollbarOpacity: 0.15,
      tableHeaderOpacity: 0.05, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.08,
      badgeBgOpacity: 0.12, badgeRadius: 999,
      btnHoverAnim: 'lift', cardHoverAnim: 'lift',
      archDensity: 'normal', archHeadingTracking: 1, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'card',
    },
  },
  {
    id: 'editorial',
    name: 'Редакционный',
    description: 'Журнальная эстетика — serif, воздух',
    icon: '▤',
    tokens: {
      btnRadius: 2, btnStyle: 'ghost', btnTransform: 'uppercase', btnWeight: 500,
      btnPaddingH: 18, btnPaddingV: 8,
      btnHoverAnim: 'fill', cardHoverAnim: 'dim',
      fontFamily: 'Georgia, "Times New Roman", serif',
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.06, lineHeight: 1.7, typeScale: 1.333,
      paragraphSpacing: 1.0,
      glassBlur: 8, glassOpacity: 0.40, glassBorderOpacity: 0.04, glassSaturation: 110,
      shadowOffsetY: 2, shadowBlurRadius: 12, shadowOpacity: 0.03,
      cardRadius: 4, inputRadius: 2, chipRadius: 2, modalRadius: 6,
      animDuration: 200, animEasing: 'cubic-bezier(0.33,1,0.68,1)',
      borderWidth: 1, gridGap: 20,
      accentHue: 20, accentSaturation: 40, accentLightness: 45,
      darkElevation: 5, darkSaturation: 30,
      inputBgOpacity: 0.03, inputBorderOpacity: 0.10, inputPaddingH: 12, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.04, chipBorderOpacity: 0.08, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 2, navItemPaddingH: 14, navItemPaddingV: 7,
      statusBgOpacity: 0.08, statusPillRadius: 2,
      modalOverlayOpacity: 0.30, dropdownBlur: 8,
      scrollbarWidth: 3, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.03, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.06,
      badgeBgOpacity: 0.10, badgeRadius: 2,
      archDensity: 'airy', archHeadingTracking: 6, archHeadingCase: 'uppercase',
      archDivider: 'gradient', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'neomorphism',
    name: 'Неоморфизм',
    description: 'Мягкие тени — 3D эффект без границ',
    icon: '◎',
    tokens: {
      btnRadius: 14, btnStyle: 'soft', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.02, lineHeight: 1.55, typeScale: 1.2,
      glassBlur: 0, glassOpacity: 0.01, glassBorderOpacity: 0, glassSaturation: 100,
      shadowOffsetY: 6, shadowBlurRadius: 16, shadowSpread: -2, shadowOpacity: 0.12,
      cardRadius: 18, inputRadius: 10, chipRadius: 14, modalRadius: 20,
      animDuration: 250, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 0, borderStyle: 'none', gridGap: 16,
      accentHue: 220, accentSaturation: 20, accentLightness: 55,
      darkElevation: 10, darkSaturation: 35,
      inputBgOpacity: 0.06, inputBorderOpacity: 0.00, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.07, chipBorderOpacity: 0.00, chipPaddingH: 10, chipPaddingV: 4,
      navItemRadius: 12, navItemPaddingH: 14, navItemPaddingV: 8,
      statusBgOpacity: 0.08, statusPillRadius: 14,
      modalOverlayOpacity: 0.25, dropdownBlur: 0,
      scrollbarWidth: 5, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.00,
      badgeBgOpacity: 0.12, badgeRadius: 14,
      btnHoverAnim: 'scale', cardHoverAnim: 'lift',
      archDensity: 'airy', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  /* ── New presets ─────────────────────────────────── */
  {
    id: 'glassmorphism',
    name: 'Стекло',
    description: 'Матовое стекло — как iOS / macOS',
    icon: '❖',
    tokens: {
      btnRadius: 12, btnStyle: 'soft', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.02, lineHeight: 1.5, typeScale: 1.2,
      glassBlur: 32, glassOpacity: 0.30, glassBorderOpacity: 0.12, glassSaturation: 180,
      shadowOffsetY: 12, shadowBlurRadius: 40, shadowSpread: 0, shadowOpacity: 0.08,
      cardRadius: 16, inputRadius: 10, chipRadius: 999, modalRadius: 20,
      animDuration: 200, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 1, borderStyle: 'solid', gridGap: 16,
      accentHue: 230, accentSaturation: 50, accentLightness: 58,
      darkElevation: 8, darkSaturation: 45,
      inputBgOpacity: 0.08, inputBorderOpacity: 0.10, inputPaddingH: 12, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.10, chipBorderOpacity: 0.08, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 10, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.12, statusPillRadius: 999,
      modalOverlayOpacity: 0.25, dropdownBlur: 24,
      scrollbarWidth: 4, scrollbarOpacity: 0.12,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.08,
      badgeBgOpacity: 0.15, badgeRadius: 999,
      btnHoverAnim: 'sheen', cardHoverAnim: 'reveal',
      archDensity: 'normal', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'slide', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'luxury',
    name: 'Люкс',
    description: 'Премиум — тёмные тона, золотой акцент',
    icon: '♦',
    tokens: {
      btnRadius: 2, btnStyle: 'filled', btnTransform: 'uppercase', btnWeight: 500,
      btnPaddingH: 24, btnPaddingV: 10,
      fontFamily: 'Georgia, "Times New Roman", serif',
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.1, lineHeight: 1.6, typeScale: 1.25,
      paragraphSpacing: 1.0,
      glassBlur: 10, glassOpacity: 0.55, glassBorderOpacity: 0.08, glassSaturation: 110,
      shadowOffsetY: 4, shadowBlurRadius: 20, shadowSpread: 0, shadowOpacity: 0.06,
      cardRadius: 4, inputRadius: 3, chipRadius: 4, modalRadius: 6,
      animDuration: 240, animEasing: 'cubic-bezier(0.33,1,0.68,1)',
      borderWidth: 1, borderStyle: 'solid', gridGap: 20,
      accentHue: 42, accentSaturation: 70, accentLightness: 50,
      darkElevation: 3, darkSaturation: 25,
      inputBgOpacity: 0.03, inputBorderOpacity: 0.12, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.05, chipBorderOpacity: 0.10, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 2, navItemPaddingH: 16, navItemPaddingV: 8,
      statusBgOpacity: 0.10, statusPillRadius: 2,
      modalOverlayOpacity: 0.45, dropdownBlur: 10,
      scrollbarWidth: 3, scrollbarOpacity: 0.08,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.08,
      badgeBgOpacity: 0.12, badgeRadius: 2,
      btnHoverAnim: 'fill', cardHoverAnim: 'dim',
      archDensity: 'grand', archHeadingTracking: 4, archHeadingCase: 'uppercase',
      archDivider: 'gradient', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'playful',
    name: 'Игровой',
    description: 'Яркий и весёлый — как Figma / Notion AI',
    icon: '●',
    tokens: {
      btnRadius: 999, btnStyle: 'filled', btnTransform: 'none', btnWeight: 600,
      btnPaddingH: 0, btnPaddingV: 0,
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.01, lineHeight: 1.55, typeScale: 1.25,
      glassBlur: 20, glassOpacity: 0.50, glassBorderOpacity: 0.06, glassSaturation: 160,
      shadowOffsetY: 8, shadowBlurRadius: 28, shadowSpread: 0, shadowOpacity: 0.07,
      cardRadius: 22, inputRadius: 14, chipRadius: 999, modalRadius: 24,
      animDuration: 200, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 0, gridGap: 16,
      accentHue: 270, accentSaturation: 65, accentLightness: 55,
      darkElevation: 8, darkSaturation: 55,
      inputBgOpacity: 0.07, inputBorderOpacity: 0.00, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.10, chipBorderOpacity: 0.00, chipPaddingH: 12, chipPaddingV: 5,
      navItemRadius: 999, navItemPaddingH: 14, navItemPaddingV: 8,
      statusBgOpacity: 0.12, statusPillRadius: 999,
      modalOverlayOpacity: 0.25, dropdownBlur: 18,
      scrollbarWidth: 6, scrollbarOpacity: 0.15,
      tableHeaderOpacity: 0.05, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.04,
      badgeBgOpacity: 0.18, badgeRadius: 999,
      btnHoverAnim: 'scale', cardHoverAnim: 'lift',
      archDensity: 'normal', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'slide', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'swiss',
    name: 'Швейцарский',
    description: 'Швейцарский стиль — Helvetica, сетка, порядок',
    icon: '▦',
    tokens: {
      btnRadius: 0, btnStyle: 'filled', btnTransform: 'uppercase', btnWeight: 500,
      btnPaddingH: 18, btnPaddingV: 9,
      fontFamily: '-apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif',
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.04, lineHeight: 1.45, typeScale: 1.333,
      paragraphSpacing: 0.5,
      glassBlur: 0, glassOpacity: 0.95, glassBorderOpacity: 0.0, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 100, animEasing: 'linear',
      borderWidth: 2, borderStyle: 'solid', gridGap: 16, gridColumns: 12,
      accentHue: 0, accentSaturation: 85, accentLightness: 50,
      darkElevation: 2, darkSaturation: 10,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.18, inputPaddingH: 10, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.18, chipPaddingH: 8, chipPaddingV: 3,
      navItemRadius: 0, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.10, statusPillRadius: 0,
      modalOverlayOpacity: 0.40, dropdownBlur: 0,
      scrollbarWidth: 4, scrollbarOpacity: 0.20,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.12,
      badgeBgOpacity: 0.14, badgeRadius: 0,
      btnHoverAnim: 'fill', cardHoverAnim: 'border',
      archDensity: 'normal', archHeadingTracking: 4, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'arrow', archSectionStyle: 'flat',
    },
  },
  {
    id: 'monochrome',
    name: 'Монохром',
    description: 'Чисто чёрно-белый, без лишнего цвета',
    icon: '◒',
    tokens: {
      btnRadius: 4, btnStyle: 'outline', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.03, lineHeight: 1.55, typeScale: 1.2,
      glassBlur: 12, glassOpacity: 0.45, glassBorderOpacity: 0.08, glassSaturation: 100,
      shadowOffsetY: 4, shadowBlurRadius: 16, shadowSpread: 0, shadowOpacity: 0.05,
      cardRadius: 8, inputRadius: 4, chipRadius: 6, modalRadius: 10,
      animDuration: 150, animEasing: 'ease',
      borderWidth: 1, borderStyle: 'solid', gridGap: 14,
      accentHue: 0, accentSaturation: 0, accentLightness: 30,
      darkElevation: 5, darkSaturation: 0,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.10, inputPaddingH: 10, inputPaddingV: 7, inputFontSize: 0,
      chipBgOpacity: 0.06, chipBorderOpacity: 0.08, chipPaddingH: 8, chipPaddingV: 2,
      navItemRadius: 4, navItemPaddingH: 10, navItemPaddingV: 5,
      statusBgOpacity: 0.08, statusPillRadius: 6,
      modalOverlayOpacity: 0.35, dropdownBlur: 10,
      scrollbarWidth: 3, scrollbarOpacity: 0.12,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.08,
      badgeBgOpacity: 0.10, badgeRadius: 6,
      btnHoverAnim: 'none', cardHoverAnim: 'dim',
      archDensity: 'normal', archHeadingTracking: 2, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'flat',
    },
  },
  {
    id: 'scandinavian',
    name: 'Скандинавский',
    description: 'Воздушный и тёплый — скандинавский уют',
    icon: '◇',
    tokens: {
      btnRadius: 8, btnStyle: 'soft', btnTransform: 'none', btnWeight: 400,
      btnPaddingH: 0, btnPaddingV: 0,
      fontWeight: 400, headingWeight: 500, letterSpacing: 0.02, lineHeight: 1.65, typeScale: 1.15,
      paragraphSpacing: 1.0,
      glassBlur: 16, glassOpacity: 0.40, glassBorderOpacity: 0.04, glassSaturation: 120,
      shadowOffsetY: 6, shadowBlurRadius: 24, shadowSpread: 0, shadowOpacity: 0.04,
      cardRadius: 16, inputRadius: 8, chipRadius: 10, modalRadius: 16,
      animDuration: 250, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 0, gridGap: 20,
      accentHue: 30, accentSaturation: 25, accentLightness: 52,
      darkElevation: 7, darkSaturation: 30,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.00, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.06, chipBorderOpacity: 0.00, chipPaddingH: 10, chipPaddingV: 4,
      navItemRadius: 8, navItemPaddingH: 14, navItemPaddingV: 7,
      statusBgOpacity: 0.08, statusPillRadius: 10,
      modalOverlayOpacity: 0.25, dropdownBlur: 16,
      scrollbarWidth: 4, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.03, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.04,
      badgeBgOpacity: 0.10, badgeRadius: 10,
      btnHoverAnim: 'lift', cardHoverAnim: 'lift',
      archDensity: 'airy', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'dashboard',
    name: 'Дашборд',
    description: 'Компактный — как Grafana / Datadog',
    icon: '▥',
    tokens: {
      btnRadius: 4, btnStyle: 'filled', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 12, btnPaddingV: 5,
      fontSize: 0.88,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.02, lineHeight: 1.4, typeScale: 1.125,
      paragraphSpacing: 0.5,
      glassBlur: 10, glassOpacity: 0.60, glassBorderOpacity: 0.1, glassSaturation: 110,
      shadowOffsetY: 2, shadowBlurRadius: 8, shadowSpread: 0, shadowOpacity: 0.04,
      cardRadius: 6, inputRadius: 4, chipRadius: 4, modalRadius: 8,
      animDuration: 120, animEasing: 'ease',
      borderWidth: 1, borderStyle: 'solid', gridGap: 10, gridColumns: 12,
      accentHue: 210, accentSaturation: 55, accentLightness: 50,
      containerWidth: 1320,
      darkElevation: 4, darkSaturation: 40,
      inputBgOpacity: 0.05, inputBorderOpacity: 0.08, inputPaddingH: 8, inputPaddingV: 5, inputFontSize: 0,
      chipBgOpacity: 0.06, chipBorderOpacity: 0.06, chipPaddingH: 6, chipPaddingV: 2,
      navItemRadius: 4, navItemPaddingH: 8, navItemPaddingV: 4,
      statusBgOpacity: 0.10, statusPillRadius: 4,
      modalOverlayOpacity: 0.35, dropdownBlur: 10,
      scrollbarWidth: 3, scrollbarOpacity: 0.12,
      tableHeaderOpacity: 0.05, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.08,
      badgeBgOpacity: 0.12, badgeRadius: 4,
      btnHoverAnim: 'none', cardHoverAnim: 'border',
      archDensity: 'dense', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'apple',
    name: 'Apple HIG',
    description: 'Чистый стиль Apple — SF Pro, мягкость',
    icon: '◆',
    tokens: {
      btnRadius: 10, btnStyle: 'filled', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 18, btnPaddingV: 8,
      fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "Helvetica Neue", sans-serif',
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.01, lineHeight: 1.47, typeScale: 1.2,
      glassBlur: 20, glassOpacity: 0.72, glassBorderOpacity: 0.08, glassSaturation: 180,
      shadowOffsetY: 4, shadowBlurRadius: 16, shadowSpread: 0, shadowOpacity: 0.06,
      cardRadius: 12, inputRadius: 8, chipRadius: 8, modalRadius: 14,
      animDuration: 180, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 0, gridGap: 16,
      accentHue: 215, accentSaturation: 90, accentLightness: 50,
      darkElevation: 6, darkSaturation: 50,
      inputBgOpacity: 0.05, inputBorderOpacity: 0.00, inputPaddingH: 12, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.07, chipBorderOpacity: 0.00, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 8, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.10, statusPillRadius: 999,
      modalOverlayOpacity: 0.30, dropdownBlur: 20,
      scrollbarWidth: 4, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.03, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.06,
      badgeBgOpacity: 0.12, badgeRadius: 999,
      btnHoverAnim: 'scale', cardHoverAnim: 'lift',
      archDensity: 'airy', archHeadingTracking: -1, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'retro',
    name: 'Ретро-терминал',
    description: 'Терминал 80-х — моноширинный, зелёный',
    icon: '▮',
    tokens: {
      btnRadius: 0, btnStyle: 'outline', btnTransform: 'uppercase', btnWeight: 400,
      btnPaddingH: 16, btnPaddingV: 7,
      fontFamily: '"JetBrains Mono", "Courier New", monospace',
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.06, lineHeight: 1.5, typeScale: 1.125,
      paragraphSpacing: 0.75,
      glassBlur: 0, glassOpacity: 0.92, glassBorderOpacity: 0.15, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 12, shadowSpread: 0, shadowOpacity: 0.15,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 50, animEasing: 'linear',
      borderWidth: 1, borderStyle: 'solid', gridGap: 12,
      accentHue: 120, accentSaturation: 80, accentLightness: 45,
      darkElevation: 2, darkSaturation: 60,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.15, inputPaddingH: 8, inputPaddingV: 6, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.15, chipPaddingH: 6, chipPaddingV: 2,
      navItemRadius: 0, navItemPaddingH: 8, navItemPaddingV: 4,
      statusBgOpacity: 0.10, statusPillRadius: 0,
      modalOverlayOpacity: 0.50, dropdownBlur: 0,
      scrollbarWidth: 6, scrollbarOpacity: 0.25,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.12,
      badgeBgOpacity: 0.14, badgeRadius: 0,
      btnHoverAnim: 'none', cardHoverAnim: 'border',
      archDensity: 'dense', archHeadingTracking: 3, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'none', archSectionStyle: 'striped',
    },
  },
  /* ── Effect-focused presets ─────────────────────────── */
  {
    id: 'liquid-glass',
    name: 'Жидкое стекло',
    description: 'Жидкое стекло — объёмные блики, высокая насыщенность, экстремальный блюр',
    icon: '💧',
    tokens: {
      btnRadius: 24, btnStyle: 'soft', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.02, lineHeight: 1.5, typeScale: 1.25,
      glassBlur: 48, glassOpacity: 0.15, glassBorderOpacity: 0.3, glassSaturation: 200,
      shadowOffsetY: 12, shadowBlurRadius: 32, shadowSpread: 0, shadowOpacity: 0.1,
      cardRadius: 24, inputRadius: 16, chipRadius: 999, modalRadius: 32,
      animDuration: 300, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 1, borderStyle: 'solid', gridGap: 24,
      accentHue: 210, accentSaturation: 80, accentLightness: 60,
      darkElevation: 12, darkSaturation: 60,
      inputBgOpacity: 0.10, inputBorderOpacity: 0.15, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.12, chipBorderOpacity: 0.15, chipPaddingH: 12, chipPaddingV: 6,
      navItemRadius: 16, navItemPaddingH: 14, navItemPaddingV: 10,
      statusBgOpacity: 0.15, statusPillRadius: 999,
      modalOverlayOpacity: 0.35, dropdownBlur: 32,
      scrollbarWidth: 6, scrollbarOpacity: 0.15,
      tableHeaderOpacity: 0.08, tableRowHoverOpacity: 0.05, tableBorderOpacity: 0.1,
      badgeBgOpacity: 0.2, badgeRadius: 999,
      btnHoverAnim: 'sheen', cardHoverAnim: 'reveal',
      archDensity: 'airy', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'glow',
    name: 'Свечение',
    description: 'Неоновое свечение — яркие акценты, глубокие тени',
    icon: '✦',
    tokens: {
      btnRadius: 10, btnStyle: 'filled', btnTransform: 'none', btnWeight: 600,
      btnPaddingH: 22, btnPaddingV: 10,
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.01, lineHeight: 1.5, typeScale: 1.2,
      glassBlur: 24, glassOpacity: 0.25, glassBorderOpacity: 0.15, glassSaturation: 200,
      shadowOffsetY: 0, shadowBlurRadius: 32, shadowSpread: 0, shadowOpacity: 0.20,
      cardRadius: 16, inputRadius: 8, chipRadius: 999, modalRadius: 18,
      animDuration: 200, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 1, borderStyle: 'solid', gridGap: 16,
      accentHue: 265, accentSaturation: 80, accentLightness: 60,
      darkElevation: 10, darkSaturation: 70,
      inputBgOpacity: 0.08, inputBorderOpacity: 0.12, inputPaddingH: 14, inputPaddingV: 9, inputFontSize: 0,
      chipBgOpacity: 0.12, chipBorderOpacity: 0.10, chipPaddingH: 10, chipPaddingV: 4,
      navItemRadius: 10, navItemPaddingH: 14, navItemPaddingV: 7,
      statusBgOpacity: 0.15, statusPillRadius: 999,
      modalOverlayOpacity: 0.45, dropdownBlur: 24,
      scrollbarWidth: 4, scrollbarOpacity: 0.18,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.05, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.20, badgeRadius: 999,
      btnHoverAnim: 'glow', cardHoverAnim: 'reveal',
      archDensity: 'normal', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'slide', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'ink',
    name: 'Ink & Paper',
    description: 'Минимализм пера — тонкие линии, ghost-кнопки',
    icon: '✎',
    tokens: {
      btnRadius: 0, btnStyle: 'ghost', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 16, btnPaddingV: 8,
      fontFamily: 'Georgia, "Times New Roman", serif',
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.04, lineHeight: 1.7, typeScale: 1.25,
      paragraphSpacing: 1.0,
      glassBlur: 0, glassOpacity: 0.96, glassBorderOpacity: 0.0, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 150, animEasing: 'ease',
      borderWidth: 1, borderStyle: 'solid', gridGap: 20,
      accentHue: 0, accentSaturation: 0, accentLightness: 15,
      darkElevation: 3, darkSaturation: 0,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.12, inputPaddingH: 10, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.10, chipPaddingH: 8, chipPaddingV: 2,
      navItemRadius: 0, navItemPaddingH: 10, navItemPaddingV: 6,
      statusBgOpacity: 0.06, statusPillRadius: 0,
      modalOverlayOpacity: 0.30, dropdownBlur: 0,
      scrollbarWidth: 2, scrollbarOpacity: 0.08,
      tableHeaderOpacity: 0.00, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.08, badgeRadius: 0,
      btnHoverAnim: 'none', cardHoverAnim: 'none',
      archDensity: 'airy', archHeadingTracking: 4, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    description: 'Сочный и выпуклый — как детский конструктор',
    icon: '◕',
    tokens: {
      btnRadius: 999, btnStyle: 'filled', btnTransform: 'none', btnWeight: 700,
      btnPaddingH: 26, btnPaddingV: 12,
      fontWeight: 500, headingWeight: 800, letterSpacing: 0.00, lineHeight: 1.5, typeScale: 1.25,
      glassBlur: 18, glassOpacity: 0.50, glassBorderOpacity: 0.06, glassSaturation: 180,
      shadowOffsetY: 8, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0.00,
      cardRadius: 24, inputRadius: 999, chipRadius: 999, modalRadius: 28,
      animDuration: 180, animEasing: 'cubic-bezier(0.34,1.56,0.64,1)',
      borderWidth: 2, borderStyle: 'solid', gridGap: 18,
      accentHue: 330, accentSaturation: 80, accentLightness: 55,
      darkElevation: 10, darkSaturation: 65,
      inputBgOpacity: 0.08, inputBorderOpacity: 0.12, inputPaddingH: 18, inputPaddingV: 12, inputFontSize: 0,
      chipBgOpacity: 0.12, chipBorderOpacity: 0.10, chipPaddingH: 14, chipPaddingV: 6,
      navItemRadius: 999, navItemPaddingH: 16, navItemPaddingV: 9,
      statusBgOpacity: 0.15, statusPillRadius: 999,
      modalOverlayOpacity: 0.20, dropdownBlur: 18,
      scrollbarWidth: 8, scrollbarOpacity: 0.20,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.05, tableBorderOpacity: 0.06,
      badgeBgOpacity: 0.20, badgeRadius: 999,
      btnHoverAnim: 'scale', cardHoverAnim: 'lift',
      archDensity: 'airy', archHeadingTracking: -2, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'slide', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Чертёжный стиль — тонкие рамки, dashed-линии',
    icon: '⊞',
    tokens: {
      btnRadius: 2, btnStyle: 'outline', btnTransform: 'uppercase', btnWeight: 500,
      btnPaddingH: 16, btnPaddingV: 7,
      fontFamily: '"JetBrains Mono", "Courier New", monospace',
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.06, lineHeight: 1.5, typeScale: 1.15,
      glassBlur: 0, glassOpacity: 0.95, glassBorderOpacity: 0.10, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0,
      cardRadius: 2, inputRadius: 2, chipRadius: 2, modalRadius: 4,
      animDuration: 80, animEasing: 'linear',
      borderWidth: 1, borderStyle: 'dashed', gridGap: 14,
      accentHue: 210, accentSaturation: 70, accentLightness: 50,
      darkElevation: 3, darkSaturation: 45,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.15, inputPaddingH: 8, inputPaddingV: 6, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.15, chipPaddingH: 6, chipPaddingV: 2,
      navItemRadius: 2, navItemPaddingH: 10, navItemPaddingV: 5,
      statusBgOpacity: 0.08, statusPillRadius: 2,
      modalOverlayOpacity: 0.35, dropdownBlur: 0,
      scrollbarWidth: 3, scrollbarOpacity: 0.15,
      tableHeaderOpacity: 0.05, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.12,
      badgeBgOpacity: 0.12, badgeRadius: 2,
      btnHoverAnim: 'none', cardHoverAnim: 'border',
      archDensity: 'dense', archHeadingTracking: 3, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'arrow', archSectionStyle: 'striped',
    },
  },
  /* ── Architectural / Award-winning site presets ───── */
  {
    id: 'minale',
    name: 'Minale + Mann',
    description: 'minaleandmann.com — чёрный фон, белый текст, weight 400, ultra-wide трекинг, ghost-кнопки, монументальная типографика',
    icon: '▯',
    tokens: {
      btnRadius: 0, btnStyle: 'ghost', btnTransform: 'uppercase', btnWeight: 400,
      btnPaddingH: 24, btnPaddingV: 10, btnSize: 'lg',
      btnHoverAnim: 'lift', cardHoverAnim: 'dim',
      fontFamily: '"Helvetica Neue", "Arial", "Segoe UI", sans-serif',
      fontSize: 1, fontWeight: 400, headingWeight: 400, letterSpacing: 0.12, lineHeight: 1.8, typeScale: 1.414,
      paragraphSpacing: 2.0, wordSpacing: 0.06, textIndent: 0,
      headingLetterSpacing: 0.22, headingLineHeight: 1.05, paragraphMaxWidth: 50, textAlign: 'left',
      /* ── TRUE BLACK + pure white — Minale+Mann ── */
      colorPageBg: '#000000', colorSurface: '#0a0a0a', colorBorder: '#ffffff',
      colorText: '#ffffff', colorHeading: '#ffffff', colorLink: '#ffffff',
      colorBtnBg: 'transparent', colorBtnText: '#ffffff',
      colorNavBg: '#000000', colorMuted: '#888888',
      colorInputBg: 'transparent', colorTagBg: 'transparent', colorTagText: '#ffffff',
      colorCardBg: '#0a0a0a',
      accentHue: 0, accentSaturation: 0, accentLightness: 100,
      successHue: 160, successSaturation: 10, errorHue: 0, errorSaturation: 20, warningHue: 42, warningSaturation: 15,
      glassBlur: 0, glassOpacity: 0.00, glassBorderOpacity: 0.05, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0.00,
      spacingBase: 8, spacingScale: 1.4,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 300, animEasing: 'ease',
      containerWidth: 860, sidebarWidth: 200, gridGap: 48, gridColumns: 12,
      borderWidth: 1, borderStyle: 'solid',
      darkElevation: 0, darkSaturation: 0,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.20, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.15, chipPaddingH: 16, chipPaddingV: 6,
      navItemRadius: 0, navItemPaddingH: 24, navItemPaddingV: 14,
      statusBgOpacity: 0.04, statusPillRadius: 0,
      modalOverlayOpacity: 0.45, dropdownBlur: 2,
      scrollbarWidth: 0, scrollbarOpacity: 0.00,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.05, badgeRadius: 0,
      focusRingWidth: 1, focusRingOffset: 4, focusRingStyle: 'solid', focusRingOpacity: 0.30,
      archDensity: 'grand', archHeadingTracking: 18, archHeadingCase: 'uppercase',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'flat',
      archNavStyle: 'minimal', archCardChrome: 'ghost', archHeroScale: 'cinematic', archVerticalRhythm: 2.4,
      archContentReveal: 'fade-up', archTextReveal: 'none',
    },
  },
  /* ── New wave presets ────────────────────────────── */
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    description: 'Геометрия и функция — первичные цвета, строгая сетка',
    icon: '△',
    tokens: {
      btnRadius: 0, btnStyle: 'filled', btnTransform: 'uppercase', btnWeight: 700,
      btnPaddingH: 20, btnPaddingV: 10,
      fontFamily: WIDE_SANS_FONT_STACK,
      fontWeight: 400, headingWeight: 800, letterSpacing: 0.06, lineHeight: 1.4, typeScale: 1.414,
      paragraphSpacing: 0.5,
      headingLetterSpacing: 0.02, headingLineHeight: 1.1,
      accentHue: 4, accentSaturation: 85, accentLightness: 50,
      successHue: 142, successSaturation: 70, errorHue: 0, errorSaturation: 85, warningHue: 48, warningSaturation: 90,
      glassBlur: 0, glassOpacity: 0.95, glassBorderOpacity: 0.0, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 80, animEasing: 'linear',
      borderWidth: 3, borderStyle: 'solid', gridGap: 16, gridColumns: 12,
      darkElevation: 2, darkSaturation: 15,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.20, inputPaddingH: 10, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.20, chipPaddingH: 8, chipPaddingV: 3,
      navItemRadius: 0, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.14, statusPillRadius: 0,
      modalOverlayOpacity: 0.45, dropdownBlur: 0,
      scrollbarWidth: 6, scrollbarOpacity: 0.25,
      tableHeaderOpacity: 0.08, tableRowHoverOpacity: 0.05, tableBorderOpacity: 0.15,
      badgeBgOpacity: 0.18, badgeRadius: 0,
      btnHoverAnim: 'fill', cardHoverAnim: 'border',
      archDensity: 'normal', archHeadingTracking: 2, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'arrow', archSectionStyle: 'striped',
    },
  },
  {
    id: 'artdeco',
    name: 'Art Deco',
    description: 'Золотой век — орнаментальный шик, контраст и элегантность',
    icon: '♢',
    tokens: {
      btnRadius: 0, btnStyle: 'outline', btnTransform: 'uppercase', btnWeight: 500,
      btnPaddingH: 28, btnPaddingV: 12,
      fontFamily: EDITORIAL_SERIF_FONT_STACK,
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.12, lineHeight: 1.6, typeScale: 1.333,
      paragraphSpacing: 1.0,
      headingLetterSpacing: 0.10, headingLineHeight: 1.15,
      accentHue: 42, accentSaturation: 80, accentLightness: 48,
      successHue: 155, successSaturation: 40, errorHue: 350, errorSaturation: 65, warningHue: 38, warningSaturation: 60,
      glassBlur: 6, glassOpacity: 0.65, glassBorderOpacity: 0.12, glassSaturation: 110,
      shadowOffsetY: 2, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 300, animEasing: 'cubic-bezier(0.33,1,0.68,1)',
      borderWidth: 2, borderStyle: 'solid', gridGap: 22,
      darkElevation: 3, darkSaturation: 25,
      inputBgOpacity: 0.02, inputBorderOpacity: 0.15, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.04, chipBorderOpacity: 0.12, chipPaddingH: 12, chipPaddingV: 4,
      navItemRadius: 0, navItemPaddingH: 18, navItemPaddingV: 8,
      statusBgOpacity: 0.10, statusPillRadius: 0,
      modalOverlayOpacity: 0.55, dropdownBlur: 6,
      scrollbarWidth: 3, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.05, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.12, badgeRadius: 0,
      btnHoverAnim: 'fill', cardHoverAnim: 'dim',
      archDensity: 'grand', archHeadingTracking: 10, archHeadingCase: 'uppercase',
      archDivider: 'gradient', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Неон на тёмном — высокий контраст, кислотные акценты',
    icon: '⚡',
    tokens: {
      btnRadius: 2, btnStyle: 'filled', btnTransform: 'uppercase', btnWeight: 700,
      btnPaddingH: 20, btnPaddingV: 9,
      fontFamily: '"JetBrains Mono", "Courier New", monospace',
      fontWeight: 400, headingWeight: 800, letterSpacing: 0.04, lineHeight: 1.45, typeScale: 1.25,
      headingLetterSpacing: 0.06, headingLineHeight: 1.1,
      accentHue: 180, accentSaturation: 100, accentLightness: 50,
      successHue: 120, successSaturation: 90, errorHue: 340, errorSaturation: 95, warningHue: 55, warningSaturation: 100,
      glassBlur: 16, glassOpacity: 0.20, glassBorderOpacity: 0.18, glassSaturation: 200,
      shadowOffsetY: 0, shadowBlurRadius: 24, shadowSpread: 0, shadowOpacity: 0.25,
      cardRadius: 2, inputRadius: 2, chipRadius: 2, modalRadius: 4,
      animDuration: 100, animEasing: 'linear',
      borderWidth: 1, borderStyle: 'solid', gridGap: 12,
      darkElevation: 12, darkSaturation: 80,
      inputBgOpacity: 0.06, inputBorderOpacity: 0.18, inputPaddingH: 10, inputPaddingV: 7, inputFontSize: 0,
      chipBgOpacity: 0.10, chipBorderOpacity: 0.15, chipPaddingH: 8, chipPaddingV: 3,
      navItemRadius: 2, navItemPaddingH: 10, navItemPaddingV: 5,
      statusBgOpacity: 0.18, statusPillRadius: 2,
      modalOverlayOpacity: 0.60, dropdownBlur: 16,
      scrollbarWidth: 4, scrollbarOpacity: 0.30,
      tableHeaderOpacity: 0.08, tableRowHoverOpacity: 0.06, tableBorderOpacity: 0.14,
      badgeBgOpacity: 0.22, badgeRadius: 2,
      btnHoverAnim: 'glow', cardHoverAnim: 'reveal',
      archDensity: 'dense', archHeadingTracking: 3, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'slide', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'zen',
    name: 'Zen',
    description: 'Ваби-саби — органичный, приглушённый, несовершенно прекрасный',
    icon: '☯',
    tokens: {
      btnRadius: 100, btnStyle: 'ghost', btnTransform: 'none', btnWeight: 400,
      btnPaddingH: 16, btnPaddingV: 8,
      fontFamily: HUMANIST_SANS_FONT_STACK,
      fontWeight: 300, headingWeight: 400, letterSpacing: 0.03, lineHeight: 1.75, typeScale: 1.15,
      paragraphSpacing: 1.2, wordSpacing: 0.02,
      headingLetterSpacing: 0.04, headingLineHeight: 1.3,
      accentHue: 28, accentSaturation: 18, accentLightness: 45,
      successHue: 140, successSaturation: 25, errorHue: 8, errorSaturation: 40, warningHue: 40, warningSaturation: 35,
      glassBlur: 20, glassOpacity: 0.25, glassBorderOpacity: 0.02, glassSaturation: 95,
      shadowOffsetY: 2, shadowBlurRadius: 32, shadowSpread: 0, shadowOpacity: 0.03,
      cardRadius: 6, inputRadius: 4, chipRadius: 6, modalRadius: 8,
      animDuration: 400, animEasing: 'cubic-bezier(0.22,1,0.36,1)',
      borderWidth: 0, borderStyle: 'none', gridGap: 24,
      darkElevation: 4, darkSaturation: 20,
      inputBgOpacity: 0.03, inputBorderOpacity: 0.04, inputPaddingH: 12, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.04, chipBorderOpacity: 0.00, chipPaddingH: 10, chipPaddingV: 4,
      navItemRadius: 4, navItemPaddingH: 14, navItemPaddingV: 8,
      statusBgOpacity: 0.05, statusPillRadius: 6,
      modalOverlayOpacity: 0.30, dropdownBlur: 20,
      scrollbarWidth: 2, scrollbarOpacity: 0.06,
      tableHeaderOpacity: 0.02, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.03,
      badgeBgOpacity: 0.08, badgeRadius: 6,
      btnHoverAnim: 'none', cardHoverAnim: 'dim',
      archDensity: 'airy', archHeadingTracking: 2, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'y2k',
    name: 'Y2K Futurism',
    description: 'Глянец и градиенты — ретро-будущее 2000-х',
    icon: '✿',
    tokens: {
      btnRadius: 999, btnStyle: 'filled', btnTransform: 'none', btnWeight: 700,
      btnPaddingH: 22, btnPaddingV: 11,
      fontFamily: SHARP_SANS_FONT_STACK,
      fontWeight: 400, headingWeight: 800, letterSpacing: 0.00, lineHeight: 1.45, typeScale: 1.25,
      headingLetterSpacing: -0.02, headingLineHeight: 1.1,
      accentHue: 290, accentSaturation: 75, accentLightness: 58,
      successHue: 150, successSaturation: 70, errorHue: 345, errorSaturation: 80, warningHue: 45, warningSaturation: 85,
      glassBlur: 28, glassOpacity: 0.40, glassBorderOpacity: 0.10, glassSaturation: 190,
      shadowOffsetY: 6, shadowBlurRadius: 20, shadowSpread: 0, shadowOpacity: 0.10,
      cardRadius: 20, inputRadius: 999, chipRadius: 999, modalRadius: 24,
      animDuration: 160, animEasing: 'cubic-bezier(0.34,1.56,0.64,1)',
      borderWidth: 2, borderStyle: 'solid', gridGap: 16,
      darkElevation: 10, darkSaturation: 65,
      inputBgOpacity: 0.08, inputBorderOpacity: 0.10, inputPaddingH: 16, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.12, chipBorderOpacity: 0.08, chipPaddingH: 12, chipPaddingV: 5,
      navItemRadius: 999, navItemPaddingH: 14, navItemPaddingV: 8,
      statusBgOpacity: 0.14, statusPillRadius: 999,
      modalOverlayOpacity: 0.25, dropdownBlur: 24,
      scrollbarWidth: 6, scrollbarOpacity: 0.18,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.05, tableBorderOpacity: 0.06,
      badgeBgOpacity: 0.20, badgeRadius: 999,
      btnHoverAnim: 'scale', cardHoverAnim: 'lift',
      archDensity: 'normal', archHeadingTracking: -2, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'slide', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'newspaper',
    name: 'Newspaper',
    description: 'Газетная вёрстка — плотные колонки, чёрная типографика',
    icon: '▧',
    tokens: {
      btnRadius: 0, btnStyle: 'outline', btnTransform: 'uppercase', btnWeight: 600,
      btnPaddingH: 14, btnPaddingV: 6,
      fontFamily: 'Georgia, "Times New Roman", "Noto Serif", serif',
      fontWeight: 400, headingWeight: 900, letterSpacing: 0.01, lineHeight: 1.55, typeScale: 1.5,
      paragraphSpacing: 0.5, textIndent: 1.5,
      headingLetterSpacing: -0.02, headingLineHeight: 1.05,
      paragraphMaxWidth: 65,
      accentHue: 0, accentSaturation: 0, accentLightness: 10,
      successHue: 142, successSaturation: 30, errorHue: 0, errorSaturation: 50, warningHue: 38, warningSaturation: 40,
      glassBlur: 0, glassOpacity: 0.98, glassBorderOpacity: 0.0, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 80, animEasing: 'linear',
      borderWidth: 1, borderStyle: 'solid', gridGap: 20, gridColumns: 12,
      darkElevation: 3, darkSaturation: 0,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.12, inputPaddingH: 8, inputPaddingV: 6, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.10, chipPaddingH: 6, chipPaddingV: 2,
      navItemRadius: 0, navItemPaddingH: 8, navItemPaddingV: 4,
      statusBgOpacity: 0.06, statusPillRadius: 0,
      modalOverlayOpacity: 0.40, dropdownBlur: 0,
      scrollbarWidth: 3, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.08, badgeRadius: 0,
      btnHoverAnim: 'none', cardHoverAnim: 'none',
      archDensity: 'dense', archHeadingTracking: -2, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'pastel',
    name: 'Pastel Dream',
    description: 'Нежные тона — воздушный, мечтательный, пастельная палитра',
    icon: '❋',
    tokens: {
      btnRadius: 16, btnStyle: 'soft', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      fontFamily: HUMANIST_SANS_FONT_STACK,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.01, lineHeight: 1.6, typeScale: 1.2,
      headingLetterSpacing: 0.00, headingLineHeight: 1.25,
      accentHue: 260, accentSaturation: 45, accentLightness: 72,
      successHue: 150, successSaturation: 40, errorHue: 350, errorSaturation: 50, warningHue: 35, warningSaturation: 50,
      glassBlur: 24, glassOpacity: 0.45, glassBorderOpacity: 0.04, glassSaturation: 150,
      shadowOffsetY: 8, shadowBlurRadius: 28, shadowSpread: 0, shadowOpacity: 0.06,
      cardRadius: 18, inputRadius: 12, chipRadius: 999, modalRadius: 22,
      animDuration: 240, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 0, gridGap: 18,
      darkElevation: 8, darkSaturation: 40,
      inputBgOpacity: 0.06, inputBorderOpacity: 0.00, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.08, chipBorderOpacity: 0.00, chipPaddingH: 10, chipPaddingV: 4,
      navItemRadius: 14, navItemPaddingH: 14, navItemPaddingV: 7,
      statusBgOpacity: 0.10, statusPillRadius: 999,
      modalOverlayOpacity: 0.20, dropdownBlur: 20,
      scrollbarWidth: 5, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.04,
      badgeBgOpacity: 0.14, badgeRadius: 999,
      btnHoverAnim: 'lift', cardHoverAnim: 'lift',
      archDensity: 'airy', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'tokyonoir',
    name: 'Tokyo Noir',
    description: 'Тёмный токийский UI — насыщенный, контрастный, японский минимализм',
    icon: '◈',
    tokens: {
      btnRadius: 100, btnStyle: 'filled', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 16, btnPaddingV: 8,
      fontFamily: JAPANESE_UI_FONT_STACK,
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.02, lineHeight: 1.5, typeScale: 1.2,
      headingLetterSpacing: 0.00, headingLineHeight: 1.2,
      accentHue: 340, accentSaturation: 70, accentLightness: 55,
      successHue: 160, successSaturation: 60, errorHue: 0, errorSaturation: 75, warningHue: 42, warningSaturation: 70,
      glassBlur: 18, glassOpacity: 0.15, glassBorderOpacity: 0.10, glassSaturation: 160,
      shadowOffsetY: 4, shadowBlurRadius: 20, shadowSpread: 0, shadowOpacity: 0.18,
      cardRadius: 8, inputRadius: 6, chipRadius: 6, modalRadius: 12,
      animDuration: 150, animEasing: 'cubic-bezier(0.22,1,0.36,1)',
      borderWidth: 1, borderStyle: 'solid', gridGap: 14,
      darkElevation: 10, darkSaturation: 65,
      inputBgOpacity: 0.06, inputBorderOpacity: 0.12, inputPaddingH: 12, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.08, chipBorderOpacity: 0.10, chipPaddingH: 8, chipPaddingV: 3,
      navItemRadius: 6, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.14, statusPillRadius: 6,
      modalOverlayOpacity: 0.55, dropdownBlur: 16,
      scrollbarWidth: 3, scrollbarOpacity: 0.15,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.16, badgeRadius: 6,
      btnHoverAnim: 'glow', cardHoverAnim: 'reveal',
      archDensity: 'dense', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'slide', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    description: 'Средиземноморье — тёплая глина, натуральные тона',
    icon: '◖',
    tokens: {
      btnRadius: 8, btnStyle: 'filled', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 18, btnPaddingV: 9,
      fontFamily: DISPLAY_SANS_FONT_STACK,
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.02, lineHeight: 1.6, typeScale: 1.2,
      paragraphSpacing: 0.8, wordSpacing: 0.01,
      headingLetterSpacing: 0.01, headingLineHeight: 1.2,
      accentHue: 16, accentSaturation: 55, accentLightness: 48,
      successHue: 145, successSaturation: 35, errorHue: 355, errorSaturation: 55, warningHue: 32, warningSaturation: 50,
      glassBlur: 14, glassOpacity: 0.50, glassBorderOpacity: 0.06, glassSaturation: 115,
      shadowOffsetY: 4, shadowBlurRadius: 20, shadowSpread: 0, shadowOpacity: 0.05,
      cardRadius: 10, inputRadius: 6, chipRadius: 10, modalRadius: 14,
      animDuration: 220, animEasing: 'cubic-bezier(0.33,1,0.68,1)',
      borderWidth: 1, borderStyle: 'solid', gridGap: 18,
      darkElevation: 6, darkSaturation: 35,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.08, inputPaddingH: 12, inputPaddingV: 9, inputFontSize: 0,
      chipBgOpacity: 0.06, chipBorderOpacity: 0.06, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 8, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.09, statusPillRadius: 10,
      modalOverlayOpacity: 0.35, dropdownBlur: 14,
      scrollbarWidth: 4, scrollbarOpacity: 0.12,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.07,
      badgeBgOpacity: 0.12, badgeRadius: 10,
      btnHoverAnim: 'lift', cardHoverAnim: 'dim',
      archDensity: 'airy', archHeadingTracking: 1, archHeadingCase: 'none',
      archDivider: 'gradient', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'arctic',
    name: 'Arctic',
    description: 'Ледяной — чистый, холодный, кристально-голубой',
    icon: '❅',
    tokens: {
      btnRadius: 10, btnStyle: 'soft', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 0, btnPaddingV: 0,
      fontFamily: NEO_GROTESK_FONT_STACK,
      fontWeight: 400, headingWeight: 500, letterSpacing: 0.02, lineHeight: 1.55, typeScale: 1.2,
      headingLetterSpacing: 0.00, headingLineHeight: 1.2,
      accentHue: 200, accentSaturation: 65, accentLightness: 55,
      successHue: 170, successSaturation: 50, errorHue: 355, errorSaturation: 60, warningHue: 35, warningSaturation: 55,
      glassBlur: 28, glassOpacity: 0.30, glassBorderOpacity: 0.06, glassSaturation: 170,
      shadowOffsetY: 6, shadowBlurRadius: 24, shadowSpread: 0, shadowOpacity: 0.05,
      cardRadius: 16, inputRadius: 8, chipRadius: 999, modalRadius: 18,
      animDuration: 200, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      borderWidth: 1, borderStyle: 'solid', gridGap: 16,
      darkElevation: 6, darkSaturation: 50,
      inputBgOpacity: 0.05, inputBorderOpacity: 0.06, inputPaddingH: 12, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.06, chipBorderOpacity: 0.04, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 10, navItemPaddingH: 12, navItemPaddingV: 6,
      statusBgOpacity: 0.09, statusPillRadius: 999,
      modalOverlayOpacity: 0.28, dropdownBlur: 24,
      scrollbarWidth: 4, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.05,
      badgeBgOpacity: 0.12, badgeRadius: 999,
      btnHoverAnim: 'sheen', cardHoverAnim: 'lift',
      archDensity: 'normal', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'card',
    },
  },
  /* ── Architectural DNA presets ─────────────────────────────
     Inspired by world-class architecture firm identities.
     Each one radically changes motion, colour, spacing & type. */
  {
    id: 'snohetta',
    name: 'Snøhetta',
    description: 'Северное молчание — свет как материал, пространство как тишина',
    icon: '⧆',
    tokens: {
      btnRadius: 0, btnStyle: 'ghost', btnTransform: 'uppercase', btnWeight: 300,
      btnPaddingH: 28, btnPaddingV: 12,
      btnHoverAnim: 'lift',
      fontFamily: SHARP_SANS_FONT_STACK,
      fontWeight: 300, headingWeight: 300, letterSpacing: 0.05, lineHeight: 1.80, typeScale: 1.414,
      paragraphSpacing: 1.5, wordSpacing: 0.02,
      headingLetterSpacing: 0.07, headingLineHeight: 1.05,
      accentHue: 185, accentSaturation: 22, accentLightness: 42,
      successHue: 165, successSaturation: 25, errorHue: 5, errorSaturation: 40, warningHue: 38, warningSaturation: 30,
      glassBlur: 52, glassOpacity: 0.07, glassBorderOpacity: 0.00, glassSaturation: 103,
      shadowOffsetY: 0, shadowBlurRadius: 72, shadowSpread: 0, shadowOpacity: 0.025,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 420, animEasing: 'cubic-bezier(0.22,1,0.36,1)',
      borderWidth: 0, borderStyle: 'none', gridGap: 30,
      cardHoverAnim: 'lift',
      darkElevation: 3, darkSaturation: 12,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.05, inputPaddingH: 0, inputPaddingV: 13, inputFontSize: 0,
      chipBgOpacity: 0.03, chipBorderOpacity: 0.00, chipPaddingH: 14, chipPaddingV: 5,
      navItemRadius: 0, navItemPaddingH: 20, navItemPaddingV: 12,
      statusBgOpacity: 0.04, statusPillRadius: 0,
      modalOverlayOpacity: 0.62, dropdownBlur: 52,
      scrollbarWidth: 1, scrollbarOpacity: 0.04,
      tableHeaderOpacity: 0.02, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.03,
      badgeBgOpacity: 0.06, badgeRadius: 0,
      colorPageBg: '#f7f6f3',
      archDensity: 'grand', archHeadingTracking: 7, archHeadingCase: 'uppercase',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'arrow', archSectionStyle: 'flat',
    },
  },
  {
    id: 'olsonkundig',
    name: 'Olson Kundig',
    description: 'Сырой материал — бетон, сталь, камень; руки, которые строят',
    icon: '▮',
    tokens: {
      btnRadius: 0, btnStyle: 'outline', btnTransform: 'uppercase', btnWeight: 500,
      btnPaddingH: 22, btnPaddingV: 10,
      btnHoverAnim: 'lift',
      fontFamily: DISPLAY_SANS_FONT_STACK,
      fontWeight: 400, headingWeight: 700, letterSpacing: 0.04, lineHeight: 1.5, typeScale: 1.333,
      headingLetterSpacing: -0.01, headingLineHeight: 1.1,
      accentHue: 22, accentSaturation: 52, accentLightness: 44,
      successHue: 150, successSaturation: 30, errorHue: 6, errorSaturation: 55, warningHue: 35, warningSaturation: 45,
      glassBlur: 5, glassOpacity: 0.74, glassBorderOpacity: 0.08, glassSaturation: 100,
      shadowOffsetY: 1, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0.22,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 190, animEasing: 'ease-out',
      borderWidth: 1, borderStyle: 'solid', gridGap: 18,
      cardHoverAnim: 'lift',
      darkElevation: 5, darkSaturation: 20,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.14, inputPaddingH: 10, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.05, chipBorderOpacity: 0.12, chipPaddingH: 9, chipPaddingV: 3,
      navItemRadius: 0, navItemPaddingH: 12, navItemPaddingV: 7,
      statusBgOpacity: 0.08, statusPillRadius: 0,
      modalOverlayOpacity: 0.55, dropdownBlur: 5,
      scrollbarWidth: 3, scrollbarOpacity: 0.12,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.10, badgeRadius: 0,
      colorPageBg: '#1c1a16', colorText: '#e2d9cc', colorHeading: '#ede5d8',
      archDensity: 'normal', archHeadingTracking: -1, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'underline', archSectionStyle: 'flat',
    },
  },
  {
    id: 'mvrdv',
    name: 'MVRDV',
    description: 'Данные и форма — параметрические блоки, яркая структура',
    icon: '⬛',
    tokens: {
      btnRadius: 0, btnStyle: 'filled', btnTransform: 'none', btnWeight: 600,
      btnPaddingH: 14, btnPaddingV: 8,
      btnHoverAnim: 'scale',
      fontFamily: UI_SANS_FONT_STACK,
      fontWeight: 400, headingWeight: 900, letterSpacing: 0.00, lineHeight: 1.35, typeScale: 1.333,
      headingLetterSpacing: -0.03, headingLineHeight: 1.0,
      accentHue: 52, accentSaturation: 100, accentLightness: 48,
      successHue: 135, successSaturation: 80, errorHue: 0, errorSaturation: 92, warningHue: 52, warningSaturation: 100,
      glassBlur: 0, glassOpacity: 0.97, glassBorderOpacity: 0.00, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 80, animEasing: 'linear',
      borderWidth: 2, borderStyle: 'solid', gridGap: 12, gridColumns: 12,
      cardHoverAnim: 'none',
      darkElevation: 2, darkSaturation: 12,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.22, inputPaddingH: 10, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.22, chipPaddingH: 8, chipPaddingV: 3,
      navItemRadius: 0, navItemPaddingH: 10, navItemPaddingV: 6,
      statusBgOpacity: 0.12, statusPillRadius: 0,
      modalOverlayOpacity: 0.50, dropdownBlur: 0,
      scrollbarWidth: 6, scrollbarOpacity: 0.22,
      tableHeaderOpacity: 0.08, tableRowHoverOpacity: 0.05, tableBorderOpacity: 0.14,
      badgeBgOpacity: 0.16, badgeRadius: 0,
      colorPageBg: '#ffffff', colorText: '#0a0a0a',
      archDensity: 'dense', archHeadingTracking: -3, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'none', archSectionStyle: 'striped',
    },
  },
  {
    id: 'som',
    name: 'SOM',
    description: 'Структурная ясность — инженерная точность, системный порядок',
    icon: '⊟',
    tokens: {
      btnRadius: 3, btnStyle: 'filled', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 20, btnPaddingV: 9,
      btnHoverAnim: 'lift',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif',
      fontWeight: 400, headingWeight: 600, letterSpacing: 0.01, lineHeight: 1.48, typeScale: 1.25,
      headingLetterSpacing: -0.01, headingLineHeight: 1.2,
      accentHue: 212, accentSaturation: 77, accentLightness: 45,
      successHue: 148, successSaturation: 60, errorHue: 2, errorSaturation: 70, warningHue: 38, warningSaturation: 88,
      glassBlur: 12, glassOpacity: 0.60, glassBorderOpacity: 0.08, glassSaturation: 110,
      shadowOffsetY: 2, shadowBlurRadius: 12, shadowSpread: 0, shadowOpacity: 0.06,
      cardRadius: 4, inputRadius: 3, chipRadius: 4, modalRadius: 6,
      animDuration: 160, animEasing: 'ease',
      borderWidth: 1, borderStyle: 'solid', gridGap: 16, gridColumns: 12,
      cardHoverAnim: 'lift',
      darkElevation: 5, darkSaturation: 42,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.10, inputPaddingH: 11, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.05, chipBorderOpacity: 0.08, chipPaddingH: 9, chipPaddingV: 3,
      navItemRadius: 3, navItemPaddingH: 11, navItemPaddingV: 6,
      statusBgOpacity: 0.09, statusPillRadius: 3,
      modalOverlayOpacity: 0.35, dropdownBlur: 12,
      scrollbarWidth: 3, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.03, tableBorderOpacity: 0.07,
      badgeBgOpacity: 0.11, badgeRadius: 3,
      archDensity: 'normal', archHeadingTracking: -1, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'card',
    },
  },
  {
    id: 'mad',
    name: 'MAD Architects',
    description: 'Космическая пустота — органические формы плывут в бесконечности',
    icon: '∞',
    tokens: {
      btnRadius: 999, btnStyle: 'ghost', btnTransform: 'uppercase', btnWeight: 300,
      btnPaddingH: 32, btnPaddingV: 13,
      btnHoverAnim: 'glow',
      fontFamily: SHARP_SANS_FONT_STACK,
      fontWeight: 300, headingWeight: 200, letterSpacing: 0.20, lineHeight: 1.85, typeScale: 1.25,
      paragraphSpacing: 1.3, wordSpacing: 0.07,
      headingLetterSpacing: 0.14, headingLineHeight: 1.12,
      accentHue: 196, accentSaturation: 55, accentLightness: 68,
      successHue: 170, successSaturation: 45, errorHue: 350, errorSaturation: 50, warningHue: 38, warningSaturation: 55,
      glassBlur: 38, glassOpacity: 0.10, glassBorderOpacity: 0.04, glassSaturation: 185,
      shadowOffsetY: 0, shadowBlurRadius: 60, shadowSpread: 0, shadowOpacity: 0.035,
      cardRadius: 26, inputRadius: 999, chipRadius: 999, modalRadius: 32,
      animDuration: 540, animEasing: 'cubic-bezier(0.22,1,0.36,1)',
      borderWidth: 0, borderStyle: 'none', gridGap: 26,
      cardHoverAnim: 'scale',
      darkElevation: 12, darkSaturation: 50,
      inputBgOpacity: 0.05, inputBorderOpacity: 0.04, inputPaddingH: 18, inputPaddingV: 12, inputFontSize: 0,
      chipBgOpacity: 0.07, chipBorderOpacity: 0.00, chipPaddingH: 14, chipPaddingV: 5,
      navItemRadius: 999, navItemPaddingH: 20, navItemPaddingV: 11,
      statusBgOpacity: 0.06, statusPillRadius: 999,
      modalOverlayOpacity: 0.72, dropdownBlur: 38,
      scrollbarWidth: 2, scrollbarOpacity: 0.05,
      tableHeaderOpacity: 0.03, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.03,
      badgeBgOpacity: 0.10, badgeRadius: 999,
      colorPageBg: '#07080c', colorText: '#c5d8e8', colorHeading: '#e0f2ff', colorLink: '#78b8d4',
      archDensity: 'grand', archHeadingTracking: 14, archHeadingCase: 'uppercase',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'arrow', archSectionStyle: 'flat',
    },
  },
]

/* ═══════════════════════════════════════════════════════════
   DESIGN CONCEPTS — holistic UI/UX + architecture + behaviour
   Each concept provides a COMPLETE token set covering:
   visual (colors, typography, glass) + structural (arch*) + kinetic (hover, anim)
   ═══════════════════════════════════════════════════════════ */
export const DESIGN_CONCEPTS: DesignPreset[] = [
  {
    id: 'concept-m3',
    name: 'Material 3',
    description: 'Material You: тональная элевация, плавная анимация (M3 Motion), чёткая локальная sans-типографика',
    icon: '⨁',
    tokens: {
      navLayoutPreset: 'rail',
      btnRadius: 999, btnStyle: 'filled', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 24, btnPaddingV: 10,
      fontFamily: M3_FONT_STACK,
      fontWeight: 400, headingWeight: 400, letterSpacing: 0, lineHeight: 1.5, typeScale: 1.25,
      glassBlur: 0, glassOpacity: 1, glassBorderOpacity: 0, glassSaturation: 100,
      shadowOffsetY: 1, shadowBlurRadius: 3, shadowSpread: 0, shadowOpacity: 0.1,
      cardRadius: 16, inputRadius: 4, chipRadius: 8, modalRadius: 28,
      animDuration: 250, animEasing: 'cubic-bezier(0.2, 0, 0, 1)',
      borderWidth: 0, gridGap: 16,
      accentHue: 250, accentSaturation: 40, accentLightness: 40,
      darkElevation: 4, darkSaturation: 40,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.3, inputPaddingH: 16, inputPaddingV: 16, inputFontSize: 1,
      chipBgOpacity: 0.1, chipBorderOpacity: 0, chipPaddingH: 12, chipPaddingV: 6,
      navItemRadius: 999, navItemPaddingH: 12, navItemPaddingV: 10,
      sidebarWidth: 216, navPanelGap: 10, navListGap: 6, navTransitDistance: 14, navItemStagger: 10,
      statusBgOpacity: 0.12, statusPillRadius: 8,
      modalOverlayOpacity: 0.4, dropdownBlur: 0,
      scrollbarWidth: 4, scrollbarOpacity: 0.1,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0,
      badgeBgOpacity: 0.16, badgeRadius: 999,
      btnHoverAnim: 'ripple', cardHoverAnim: 'lift',
      archDensity: 'airy', archHeadingTracking: 0, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'slide-b', archLinkAnim: 'none', archSectionStyle: 'flat',
      colorSurface: '#F4EFF4', 
      colorPageBg: '#FEF7FF', 
      colorCardBg: '#FFFFFF',
      colorBtnBg: '#6750A4', 
      colorBtnText: '#FFFFFF', 
      colorNavBg: '#F3EDF7', 
      colorText: '#1D1B20', 
      colorHeading: '#1D1B20', 
      colorMuted: '#49454F',
    },
  },
  /* ─── 1. Тишина — inspired by Minale+Mann: absolute void, content floats ── */
  {
    id: 'concept-silence',
    name: 'Тишина',
    description: 'Minale+Mann: пустота как форма. Невидимая навигация, ghost-карточки, кинематографичный масштаб, ритм ×2.5. Вес 200, спейсинг 0.12em, анимация 800ms.',
    icon: '○',
    tokens: {
      btnRadius: 0, btnStyle: 'ghost', btnTransform: 'uppercase', btnWeight: 200,
      btnPaddingH: 32, btnPaddingV: 14, btnSize: 'lg',
      btnHoverAnim: 'lift', cardHoverAnim: 'dim',
      fontFamily: NEO_GROTESK_FONT_STACK,
      fontSize: 1, fontWeight: 200, headingWeight: 200, letterSpacing: 0.12, lineHeight: 2.0, typeScale: 1.414,
      paragraphSpacing: 2.0, wordSpacing: 0.05, textIndent: 0,
      headingLetterSpacing: 0.20, headingLineHeight: 1.05, paragraphMaxWidth: 55, textAlign: 'left',
      accentHue: 35, accentSaturation: 6, accentLightness: 55,
      successHue: 160, successSaturation: 12, errorHue: 0, errorSaturation: 20, warningHue: 40, warningSaturation: 15,
      glassBlur: 64, glassOpacity: 0.03, glassBorderOpacity: 0.00, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0.00,
      spacingBase: 8, spacingScale: 1.4,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 800, animEasing: 'cubic-bezier(0.22,1,0.36,1)',
      containerWidth: 880, sidebarWidth: 200, gridGap: 48, gridColumns: 12,
      borderWidth: 0, borderStyle: 'none',
      darkElevation: 1, darkSaturation: 5,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.00, inputPaddingH: 0, inputPaddingV: 16, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.00, chipPaddingH: 16, chipPaddingV: 6,
      navItemRadius: 0, navItemPaddingH: 24, navItemPaddingV: 14,
      statusBgOpacity: 0.02, statusPillRadius: 0,
      modalOverlayOpacity: 0.70, dropdownBlur: 64,
      scrollbarWidth: 0, scrollbarOpacity: 0.00,
      tableHeaderOpacity: 0.01, tableRowHoverOpacity: 0.01, tableBorderOpacity: 0.01,
      badgeBgOpacity: 0.03, badgeRadius: 0,
      focusRingWidth: 1, focusRingOffset: 6, focusRingStyle: 'solid', focusRingOpacity: 0.15,
      archDensity: 'grand', archHeadingTracking: 20, archHeadingCase: 'uppercase',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'flat',
      archNavStyle: 'minimal', archCardChrome: 'ghost', archHeroScale: 'cinematic', archVerticalRhythm: 2.5,
      archContentReveal: 'fade-up', archTextReveal: 'blur-in',
      /* ── Dark charcoal palette — deep void ── */
      colorPageBg: '#080808', colorSurface: '#0e0e0e', colorBorder: '#ffffff',
      colorText: '#c8c8c8', colorHeading: '#f0f0f0', colorLink: '#e0e0e0',
      colorBtnBg: '#080808', colorBtnText: '#e0e0e0',
      colorNavBg: '#050505', colorMuted: '#666666',
      colorInputBg: '#080808', colorTagBg: '#0e0e0e', colorTagText: '#c8c8c8',
      colorCardBg: '#0e0e0e',
    },
  },
  /* ─── 2. Функция — mission control dashboard: ultra-dense, zero waste ──── */
  {
    id: 'concept-function',
    name: 'Функция',
    description: 'Центр управления: максимальная плотность, ритм ×0.5, компактный масштаб, мгновенные переходы 30ms. Видимый хром, острые углы.',
    icon: '▦',
    tokens: {
      btnRadius: 2, btnStyle: 'filled', btnTransform: 'none', btnWeight: 600,
      btnPaddingH: 8, btnPaddingV: 3, btnSize: 'xs',
      btnHoverAnim: 'none', cardHoverAnim: 'border',
      fontFamily: '"JetBrains Mono", "SF Mono", monospace',
      fontSize: 0.78, fontWeight: 400, headingWeight: 700, letterSpacing: 0.00, lineHeight: 1.25, typeScale: 1.067,
      paragraphSpacing: 0.2, wordSpacing: 0, textIndent: 0,
      headingLetterSpacing: -0.02, headingLineHeight: 1.1, paragraphMaxWidth: 0, textAlign: 'left',
      accentHue: 210, accentSaturation: 80, accentLightness: 55,
      successHue: 142, successSaturation: 80, errorHue: 0, errorSaturation: 80, warningHue: 38, warningSaturation: 95,
      glassBlur: 4, glassOpacity: 0.80, glassBorderOpacity: 0.14, glassSaturation: 100,
      shadowOffsetY: 1, shadowBlurRadius: 2, shadowSpread: 0, shadowOpacity: 0.06,
      spacingBase: 2, spacingScale: 1,
      cardRadius: 2, inputRadius: 2, chipRadius: 2, modalRadius: 4,
      animDuration: 30, animEasing: 'linear',
      containerWidth: 1600, sidebarWidth: 180, gridGap: 4, gridColumns: 12,
      borderWidth: 1, borderStyle: 'solid',
      darkElevation: 6, darkSaturation: 50,
      inputBgOpacity: 0.06, inputBorderOpacity: 0.14, inputPaddingH: 6, inputPaddingV: 3, inputFontSize: -1,
      chipBgOpacity: 0.08, chipBorderOpacity: 0.12, chipPaddingH: 5, chipPaddingV: 1,
      navItemRadius: 2, navItemPaddingH: 6, navItemPaddingV: 3,
      statusBgOpacity: 0.14, statusPillRadius: 2,
      modalOverlayOpacity: 0.25, dropdownBlur: 4,
      scrollbarWidth: 4, scrollbarOpacity: 0.25,
      tableHeaderOpacity: 0.08, tableRowHoverOpacity: 0.06, tableBorderOpacity: 0.14,
      badgeBgOpacity: 0.18, badgeRadius: 2,
      focusRingWidth: 2, focusRingOffset: 0, focusRingStyle: 'solid', focusRingOpacity: 1,
      archDensity: 'dense', archHeadingTracking: -3, archHeadingCase: 'none',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'underline', archSectionStyle: 'flat',
      archNavStyle: 'full', archCardChrome: 'visible', archHeroScale: 'compact', archVerticalRhythm: 0.5,
      archContentReveal: 'none', archTextReveal: 'none',
    },
  },
  /* ─── 3. Ремесло — Scandinavian warmth: organic, tactile, round ────────── */
  {
    id: 'concept-craft',
    name: 'Ремесло',
    description: 'Скандинавский уют: крупный ритм ×1.8, мягкий хром, тёплый акцент, organic скругления 24px, медленные пружинные анимации 450ms.',
    icon: '◇',
    tokens: {
      btnRadius: 16, btnStyle: 'soft', btnTransform: 'none', btnWeight: 400,
      btnPaddingH: 22, btnPaddingV: 11, btnSize: 'md',
      btnHoverAnim: 'lift', cardHoverAnim: 'lift',
      fontFamily: HUMANIST_SANS_FONT_STACK,
      fontSize: 1.02, fontWeight: 350, headingWeight: 500, letterSpacing: 0.02, lineHeight: 1.8, typeScale: 1.25,
      paragraphSpacing: 1.4, wordSpacing: 0.02, textIndent: 0,
      headingLetterSpacing: 0.01, headingLineHeight: 1.2, paragraphMaxWidth: 60, textAlign: 'left',
      accentHue: 28, accentSaturation: 40, accentLightness: 52,
      successHue: 145, successSaturation: 30, errorHue: 12, errorSaturation: 40, warningHue: 35, warningSaturation: 40,
      glassBlur: 28, glassOpacity: 0.35, glassBorderOpacity: 0.02, glassSaturation: 125,
      shadowOffsetY: 8, shadowBlurRadius: 36, shadowSpread: 0, shadowOpacity: 0.04,
      spacingBase: 6, spacingScale: 1.2,
      cardRadius: 24, inputRadius: 12, chipRadius: 14, modalRadius: 28,
      animDuration: 450, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      containerWidth: 1040, sidebarWidth: 250, gridGap: 28, gridColumns: 12,
      borderWidth: 0, borderStyle: 'none',
      darkElevation: 6, darkSaturation: 25,
      inputBgOpacity: 0.04, inputBorderOpacity: 0.00, inputPaddingH: 16, inputPaddingV: 12, inputFontSize: 0,
      chipBgOpacity: 0.06, chipBorderOpacity: 0.00, chipPaddingH: 14, chipPaddingV: 5,
      navItemRadius: 12, navItemPaddingH: 16, navItemPaddingV: 10,
      statusBgOpacity: 0.08, statusPillRadius: 14,
      modalOverlayOpacity: 0.20, dropdownBlur: 24,
      scrollbarWidth: 5, scrollbarOpacity: 0.08,
      tableHeaderOpacity: 0.03, tableRowHoverOpacity: 0.02, tableBorderOpacity: 0.03,
      badgeBgOpacity: 0.08, badgeRadius: 14,
      focusRingWidth: 2, focusRingOffset: 4, focusRingStyle: 'solid', focusRingOpacity: 0.4,
      archDensity: 'airy', archHeadingTracking: 2, archHeadingCase: 'none',
      archDivider: 'gradient', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
      archNavStyle: 'full', archCardChrome: 'subtle', archHeroScale: 'large', archVerticalRhythm: 1.8,
      archContentReveal: 'fade', archTextReveal: 'none',
      /* ── Warm parchment palette ── */
      colorPageBg: '#f8f4ee', colorSurface: '#ede8e0', colorBorder: '#c4b8a4',
      colorText: '#3a352c', colorHeading: '#2a2520', colorLink: '#7a6848',
      colorBtnBg: '#3a352c', colorBtnText: '#f8f4ee',
      colorNavBg: '#ede8e0', colorMuted: '#8a7e6e',
      colorInputBg: '#f8f4ee', colorTagBg: '#ede8e0', colorTagText: '#3a352c',
      colorCardBg: '#ede8e0',
    },
  },
  /* ─── 4. Футуризм — cyberpunk neon: glass, glow, deep black ───────────── */
  {
    id: 'concept-future',
    name: 'Футуризм',
    description: 'Киберпанк: минимальная навигация, стеклянные карточки, крупный масштаб, неон 185°/95%, глубокие тени 0.35, glow-кнопки, тёмный фон.',
    icon: '◈',
    tokens: {
      btnRadius: 100, btnStyle: 'filled', btnTransform: 'uppercase', btnWeight: 600,
      btnPaddingH: 24, btnPaddingV: 11, btnSize: 'md',
      btnHoverAnim: 'glow', cardHoverAnim: 'scale',
      fontFamily: SHARP_SANS_FONT_STACK,
      fontSize: 0.95, fontWeight: 400, headingWeight: 700, letterSpacing: 0.04, lineHeight: 1.45, typeScale: 1.333,
      paragraphSpacing: 0.8, wordSpacing: 0, textIndent: 0,
      headingLetterSpacing: 0.08, headingLineHeight: 1.05, paragraphMaxWidth: 0, textAlign: 'left',
      accentHue: 185, accentSaturation: 95, accentLightness: 55,
      successHue: 160, successSaturation: 90, errorHue: 340, errorSaturation: 95, warningHue: 50, warningSaturation: 100,
      glassBlur: 48, glassOpacity: 0.12, glassBorderOpacity: 0.18, glassSaturation: 260,
      shadowOffsetY: 0, shadowBlurRadius: 56, shadowSpread: 4, shadowOpacity: 0.35,
      spacingBase: 4, spacingScale: 1.1,
      cardRadius: 8, inputRadius: 6, chipRadius: 999, modalRadius: 12,
      animDuration: 200, animEasing: 'cubic-bezier(0.22,1,0.36,1)',
      containerWidth: 1200, sidebarWidth: 220, gridGap: 16, gridColumns: 12,
      borderWidth: 1, borderStyle: 'solid',
      darkElevation: 16, darkSaturation: 90,
      inputBgOpacity: 0.08, inputBorderOpacity: 0.18, inputPaddingH: 12, inputPaddingV: 9, inputFontSize: 0,
      chipBgOpacity: 0.14, chipBorderOpacity: 0.16, chipPaddingH: 10, chipPaddingV: 3,
      navItemRadius: 4, navItemPaddingH: 12, navItemPaddingV: 7,
      statusBgOpacity: 0.20, statusPillRadius: 999,
      modalOverlayOpacity: 0.65, dropdownBlur: 40,
      scrollbarWidth: 2, scrollbarOpacity: 0.25,
      tableHeaderOpacity: 0.08, tableRowHoverOpacity: 0.06, tableBorderOpacity: 0.16,
      badgeBgOpacity: 0.24, badgeRadius: 999,
      focusRingWidth: 2, focusRingOffset: 2, focusRingStyle: 'solid', focusRingOpacity: 1,
      archDensity: 'normal', archHeadingTracking: 6, archHeadingCase: 'uppercase',
      archDivider: 'gradient', archPageEnter: 'slide', archLinkAnim: 'arrow', archSectionStyle: 'card',
      archNavStyle: 'minimal', archCardChrome: 'subtle', archHeroScale: 'large', archVerticalRhythm: 1.2,
      archContentReveal: 'slide-up', archTextReveal: 'none',
      colorPageBg: '#06090f', colorSurface: '#0c1018', colorText: '#94c8e0', colorHeading: '#d8f0ff',
      colorLink: '#6090ff', colorBtnBg: '#6090ff', colorBtnText: '#ffffff',
      colorNavBg: '#040608', colorMuted: '#4a6878', colorCardBg: '#0c1018',
      colorInputBg: '#06090f', colorTagBg: '#0c1018', colorTagText: '#6090ff',
    },
  },
  /* ─── 5. Классика — haute editorial: serif, vast whitespace ────────────── */
  {
    id: 'concept-editorial',
    name: 'Классика',
    description: 'Haute editorial: призрачные карточки, кинематограф-масштаб, ритм ×2.2, serif, трекинг 0.15em, paragraphMaxWidth 50ch, text indent, fade 550ms.',
    icon: '▤',
    tokens: {
      btnRadius: 0, btnStyle: 'ghost', btnTransform: 'uppercase', btnWeight: 400,
      btnPaddingH: 28, btnPaddingV: 12, btnSize: 'md',
      btnHoverAnim: 'fill', cardHoverAnim: 'dim',
      fontFamily: EDITORIAL_SERIF_FONT_STACK,
      fontSize: 1.05, fontWeight: 400, headingWeight: 700, letterSpacing: 0.06, lineHeight: 1.95, typeScale: 1.414,
      paragraphSpacing: 1.8, wordSpacing: 0.01, textIndent: 2.5,
      headingLetterSpacing: 0.15, headingLineHeight: 1.05, paragraphMaxWidth: 50, textAlign: 'left',
      accentHue: 18, accentSaturation: 50, accentLightness: 40,
      successHue: 150, successSaturation: 30, errorHue: 355, errorSaturation: 50, warningHue: 35, warningSaturation: 45,
      glassBlur: 4, glassOpacity: 0.40, glassBorderOpacity: 0.02, glassSaturation: 102,
      shadowOffsetY: 2, shadowBlurRadius: 8, shadowSpread: 0, shadowOpacity: 0.02,
      spacingBase: 7, spacingScale: 1.2,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 2,
      animDuration: 550, animEasing: 'cubic-bezier(0.33,1,0.68,1)',
      containerWidth: 860, sidebarWidth: 200, gridGap: 36, gridColumns: 12,
      borderWidth: 1, borderStyle: 'solid',
      darkElevation: 3, darkSaturation: 18,
      inputBgOpacity: 0.01, inputBorderOpacity: 0.08, inputPaddingH: 14, inputPaddingV: 12, inputFontSize: 0,
      chipBgOpacity: 0.02, chipBorderOpacity: 0.06, chipPaddingH: 12, chipPaddingV: 4,
      navItemRadius: 0, navItemPaddingH: 18, navItemPaddingV: 10,
      statusBgOpacity: 0.05, statusPillRadius: 0,
      modalOverlayOpacity: 0.40, dropdownBlur: 4,
      scrollbarWidth: 1, scrollbarOpacity: 0.06,
      tableHeaderOpacity: 0.02, tableRowHoverOpacity: 0.01, tableBorderOpacity: 0.04,
      badgeBgOpacity: 0.06, badgeRadius: 0,
      focusRingWidth: 1, focusRingOffset: 4, focusRingStyle: 'dotted', focusRingOpacity: 0.35,
      archDensity: 'grand', archHeadingTracking: 15, archHeadingCase: 'uppercase',
      archDivider: 'gradient', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
      archNavStyle: 'minimal', archCardChrome: 'ghost', archHeroScale: 'cinematic', archVerticalRhythm: 2.2,
      archContentReveal: 'fade-up', archTextReveal: 'clip',
      /* ── Cream editorial palette — aged paper ── */
      colorPageBg: '#f5f0e8', colorSurface: '#ebe5da', colorBorder: '#1a1a1a',
      colorText: '#2c2820', colorHeading: '#1a1610', colorLink: '#5a4830',
      colorBtnBg: '#1a1610', colorBtnText: '#f5f0e8',
      colorNavBg: '#ebe5da', colorMuted: '#8a8070',
      colorInputBg: '#f5f0e8', colorTagBg: '#ebe5da', colorTagText: '#2c2820',
      colorCardBg: '#ebe5da',
    },
  },
  /* ─── 6. Манифест — brutalist expressive: raw, aggressive, zero decor ──── */
  {
    id: 'concept-brutal',
    name: 'Манифест',
    description: 'Брутализм: скрытая навигация, ghost-карточки, компактный масштаб, ритм ×0.6, borderWidth 4, вес 900, typeScale 1.5, анимация 0ms.',
    icon: '▬',
    tokens: {
      btnRadius: 0, btnStyle: 'outline', btnTransform: 'uppercase', btnWeight: 900,
      btnPaddingH: 24, btnPaddingV: 12, btnSize: 'md',
      btnHoverAnim: 'fill', cardHoverAnim: 'border',
      fontFamily: BRUTAL_DISPLAY_FONT_STACK,
      fontSize: 1.05, fontWeight: 500, headingWeight: 900, letterSpacing: 0.10, lineHeight: 1.2, typeScale: 1.5,
      paragraphSpacing: 0.3, wordSpacing: 0, textIndent: 0,
      headingLetterSpacing: -0.03, headingLineHeight: 0.92, paragraphMaxWidth: 0, textAlign: 'left',
      accentHue: 0, accentSaturation: 100, accentLightness: 50,
      successHue: 120, successSaturation: 90, errorHue: 0, errorSaturation: 100, warningHue: 50, warningSaturation: 100,
      glassBlur: 0, glassOpacity: 1.00, glassBorderOpacity: 0.30, glassSaturation: 100,
      shadowOffsetY: 6, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0.25,
      spacingBase: 3, spacingScale: 1,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 0, animEasing: 'linear',
      containerWidth: 1400, sidebarWidth: 200, gridGap: 6, gridColumns: 12,
      borderWidth: 4, borderStyle: 'solid',
      darkElevation: 1, darkSaturation: 5,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.30, inputPaddingH: 10, inputPaddingV: 8, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.30, chipPaddingH: 8, chipPaddingV: 3,
      navItemRadius: 0, navItemPaddingH: 10, navItemPaddingV: 6,
      statusBgOpacity: 0.18, statusPillRadius: 0,
      modalOverlayOpacity: 0.70, dropdownBlur: 0,
      scrollbarWidth: 8, scrollbarOpacity: 0.40,
      tableHeaderOpacity: 0.14, tableRowHoverOpacity: 0.08, tableBorderOpacity: 0.25,
      badgeBgOpacity: 0.22, badgeRadius: 0,
      focusRingWidth: 4, focusRingOffset: 0, focusRingStyle: 'solid', focusRingOpacity: 1,
      archDensity: 'dense', archHeadingTracking: -5, archHeadingCase: 'uppercase',
      archDivider: 'line', archPageEnter: 'none', archLinkAnim: 'arrow', archSectionStyle: 'striped',
      archNavStyle: 'hidden', archCardChrome: 'ghost', archHeroScale: 'compact', archVerticalRhythm: 0.6,
      archContentReveal: 'none', archTextReveal: 'none',
      /* ── Stark B&W — no middle ground ── */
      colorPageBg: '#ffffff', colorSurface: '#ffffff', colorBorder: '#000000',
      colorText: '#000000', colorHeading: '#000000', colorLink: '#000000',
      colorBtnBg: '#000000', colorBtnText: '#ffffff',
      colorNavBg: '#000000', colorMuted: '#555555',
      colorInputBg: '#ffffff', colorTagBg: '#000000', colorTagText: '#ffffff',
      colorCardBg: '#ffffff',
    },
  },
  /* ─── 7. Витрина — deep glass morphism: blurred layers, translucent ────── */
  {
    id: 'concept-glass',
    name: 'Витрина',
    description: 'Glass morphism: blur 64px, saturation 280, pill-формы 999px, полупрозрачный хром, slide-переходы, ритм ×1.4, scale-hover.',
    icon: '❖',
    tokens: {
      btnRadius: 999, btnStyle: 'soft', btnTransform: 'none', btnWeight: 500,
      btnPaddingH: 22, btnPaddingV: 10, btnSize: 'md',
      btnHoverAnim: 'sheen', cardHoverAnim: 'scale',
      fontFamily: SHARP_SANS_FONT_STACK,
      fontSize: 0.98, fontWeight: 400, headingWeight: 600, letterSpacing: 0.01, lineHeight: 1.55, typeScale: 1.2,
      paragraphSpacing: 0.9, wordSpacing: 0, textIndent: 0,
      headingLetterSpacing: 0.02, headingLineHeight: 1.15, paragraphMaxWidth: 0, textAlign: 'left',
      accentHue: 230, accentSaturation: 65, accentLightness: 62,
      successHue: 160, successSaturation: 60, errorHue: 350, errorSaturation: 70, warningHue: 38, warningSaturation: 75,
      glassBlur: 64, glassOpacity: 0.18, glassBorderOpacity: 0.16, glassSaturation: 280,
      shadowOffsetY: 12, shadowBlurRadius: 56, shadowSpread: 0, shadowOpacity: 0.12,
      spacingBase: 5, spacingScale: 1.1,
      cardRadius: 28, inputRadius: 18, chipRadius: 999, modalRadius: 32,
      animDuration: 280, animEasing: 'cubic-bezier(0.16,1,0.3,1)',
      containerWidth: 1140, sidebarWidth: 240, gridGap: 18, gridColumns: 12,
      borderWidth: 1, borderStyle: 'solid',
      darkElevation: 10, darkSaturation: 60,
      inputBgOpacity: 0.10, inputBorderOpacity: 0.12, inputPaddingH: 16, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.14, chipBorderOpacity: 0.10, chipPaddingH: 14, chipPaddingV: 5,
      navItemRadius: 999, navItemPaddingH: 16, navItemPaddingV: 8,
      statusBgOpacity: 0.16, statusPillRadius: 999,
      modalOverlayOpacity: 0.22, dropdownBlur: 48,
      scrollbarWidth: 4, scrollbarOpacity: 0.10,
      tableHeaderOpacity: 0.06, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.08,
      badgeBgOpacity: 0.20, badgeRadius: 999,
      focusRingWidth: 2, focusRingOffset: 3, focusRingStyle: 'solid', focusRingOpacity: 0.6,
      archDensity: 'airy', archHeadingTracking: 1, archHeadingCase: 'none',
      archDivider: 'none', archPageEnter: 'slide', archLinkAnim: 'underline', archSectionStyle: 'card',
      archNavStyle: 'full', archCardChrome: 'visible', archHeroScale: 'large', archVerticalRhythm: 1.4,
      archContentReveal: 'slide-up', archTextReveal: 'none',
    },
  },
  /* ─── 8. Грандиозность — cinematic luxury: gold, serif, vast spacing ───── */
  {
    id: 'concept-grand',
    name: 'Грандиозность',
    description: 'Кинематографичный люкс: минимальная навигация, ghost-карточки, кинематограф, ритм ×2.4, золото 42°, serif, трекинг 0.12em, fade 700ms.',
    icon: '♦',
    tokens: {
      btnRadius: 0, btnStyle: 'filled', btnTransform: 'uppercase', btnWeight: 400,
      btnPaddingH: 36, btnPaddingV: 14, btnSize: 'lg',
      btnHoverAnim: 'lift', cardHoverAnim: 'lift',
      fontFamily: EDITORIAL_SERIF_FONT_STACK,
      fontSize: 1.1, fontWeight: 300, headingWeight: 700, letterSpacing: 0.08, lineHeight: 1.85, typeScale: 1.414,
      paragraphSpacing: 1.8, wordSpacing: 0.03, textIndent: 0,
      headingLetterSpacing: 0.12, headingLineHeight: 1.02, paragraphMaxWidth: 50, textAlign: 'left',
      accentHue: 42, accentSaturation: 80, accentLightness: 50,
      successHue: 155, successSaturation: 35, errorHue: 350, errorSaturation: 55, warningHue: 38, warningSaturation: 50,
      glassBlur: 8, glassOpacity: 0.50, glassBorderOpacity: 0.04, glassSaturation: 108,
      shadowOffsetY: 4, shadowBlurRadius: 32, shadowSpread: 0, shadowOpacity: 0.05,
      spacingBase: 8, spacingScale: 1.3,
      cardRadius: 2, inputRadius: 0, chipRadius: 2, modalRadius: 4,
      animDuration: 700, animEasing: 'cubic-bezier(0.33,1,0.68,1)',
      containerWidth: 920, sidebarWidth: 240, gridGap: 40, gridColumns: 12,
      borderWidth: 1, borderStyle: 'solid',
      darkElevation: 3, darkSaturation: 20,
      inputBgOpacity: 0.02, inputBorderOpacity: 0.08, inputPaddingH: 18, inputPaddingV: 13, inputFontSize: 0,
      chipBgOpacity: 0.03, chipBorderOpacity: 0.06, chipPaddingH: 14, chipPaddingV: 5,
      navItemRadius: 0, navItemPaddingH: 22, navItemPaddingV: 12,
      statusBgOpacity: 0.06, statusPillRadius: 0,
      modalOverlayOpacity: 0.55, dropdownBlur: 8,
      scrollbarWidth: 2, scrollbarOpacity: 0.05,
      tableHeaderOpacity: 0.02, tableRowHoverOpacity: 0.01, tableBorderOpacity: 0.04,
      badgeBgOpacity: 0.08, badgeRadius: 2,
      focusRingWidth: 1, focusRingOffset: 5, focusRingStyle: 'solid', focusRingOpacity: 0.3,
      archDensity: 'grand', archHeadingTracking: 12, archHeadingCase: 'uppercase',
      archDivider: 'gradient', archPageEnter: 'fade', archLinkAnim: 'underline', archSectionStyle: 'flat',
      archNavStyle: 'minimal', archCardChrome: 'ghost', archHeroScale: 'cinematic', archVerticalRhythm: 2.4,
      archContentReveal: 'fade-up', archTextReveal: 'clip',
      /* ── Dark gold luxury palette ── */
      colorPageBg: '#0a0908', colorSurface: '#12100e', colorBorder: '#c8a96e',
      colorText: '#bfb7a8', colorHeading: '#e8dcc8', colorLink: '#c8a96e',
      colorBtnBg: '#0a0908', colorBtnText: '#c8a96e',
      colorNavBg: '#080706', colorMuted: '#6e6558',
      colorInputBg: '#0a0908', colorTagBg: '#12100e', colorTagText: '#c8a96e',
      colorCardBg: '#12100e',
    },
  },
  /* ─── 9. Minale + Mann — the definitive minaleandmann.com style ─────── */
  {
    id: 'concept-minale',
    name: 'Minale + Mann',
    description: 'minaleandmann.com: чёрный фон #000, белый текст, вес 400, спейсинг 0.22em, 300ms переходы, ghost-кнопки, минималистичные инпуты',
    icon: '▯',
    tokens: {
      btnRadius: 0, btnStyle: 'ghost', btnTransform: 'uppercase', btnWeight: 400,
      btnPaddingH: 24, btnPaddingV: 10, btnSize: 'lg',
      btnHoverAnim: 'lift', cardHoverAnim: 'dim',
      fontFamily: NEO_GROTESK_FONT_STACK,
      fontSize: 1, fontWeight: 400, headingWeight: 400, letterSpacing: 0.12, lineHeight: 1.8, typeScale: 1.414,
      paragraphSpacing: 2.0, wordSpacing: 0.06, textIndent: 0,
      headingLetterSpacing: 0.22, headingLineHeight: 1.05, paragraphMaxWidth: 50, textAlign: 'left',
      /* ── TRUE BLACK + pure white — Minale+Mann ── */
      colorPageBg: '#000000', colorSurface: '#0a0a0a', colorBorder: '#ffffff',
      colorText: '#ffffff', colorHeading: '#ffffff', colorLink: '#ffffff',
      colorBtnBg: 'transparent', colorBtnText: '#ffffff',
      colorNavBg: '#000000', colorMuted: '#888888',
      colorInputBg: 'transparent', colorTagBg: 'transparent', colorTagText: '#ffffff',
      colorCardBg: '#0a0a0a',
      accentHue: 0, accentSaturation: 0, accentLightness: 100,
      successHue: 160, successSaturation: 10, errorHue: 0, errorSaturation: 20, warningHue: 42, warningSaturation: 15,
      glassBlur: 0, glassOpacity: 0.00, glassBorderOpacity: 0.10, glassSaturation: 100,
      shadowOffsetY: 0, shadowBlurRadius: 0, shadowSpread: 0, shadowOpacity: 0.00,
      spacingBase: 8, spacingScale: 1.4,
      cardRadius: 0, inputRadius: 0, chipRadius: 0, modalRadius: 0,
      animDuration: 300, animEasing: 'ease',
      containerWidth: 860, sidebarWidth: 200, gridGap: 48, gridColumns: 12,
      borderWidth: 1, borderStyle: 'solid',
      darkElevation: 0, darkSaturation: 0,
      inputBgOpacity: 0.00, inputBorderOpacity: 0.20, inputPaddingH: 14, inputPaddingV: 10, inputFontSize: 0,
      chipBgOpacity: 0.00, chipBorderOpacity: 0.15, chipPaddingH: 16, chipPaddingV: 6,
      navItemRadius: 0, navItemPaddingH: 24, navItemPaddingV: 14,
      statusBgOpacity: 0.04, statusPillRadius: 0,
      modalOverlayOpacity: 0.45, dropdownBlur: 2,
      scrollbarWidth: 0, scrollbarOpacity: 0.00,
      tableHeaderOpacity: 0.04, tableRowHoverOpacity: 0.04, tableBorderOpacity: 0.10,
      badgeBgOpacity: 0.05, badgeRadius: 0,
      focusRingWidth: 1, focusRingOffset: 4, focusRingStyle: 'solid', focusRingOpacity: 0.30,
      archDensity: 'grand', archHeadingTracking: 18, archHeadingCase: 'uppercase',
      archDivider: 'none', archPageEnter: 'fade', archLinkAnim: 'none', archSectionStyle: 'flat',
      archNavStyle: 'minimal', archCardChrome: 'ghost', archHeroScale: 'cinematic', archVerticalRhythm: 2.4,
      archContentReveal: 'fade-up', archTextReveal: 'none',
    },
  },
]

/* ═══════════════════════════════════════════════════════════
   FONT CATALOGUE
   ═══════════════════════════════════════════════════════════ */
export const FONT_OPTIONS = [
  { id: 'system',    label: 'System UI',      value: SYSTEM_UI_FONT_STACK },
  { id: 'roboto',    label: 'M3 Sans',        value: M3_FONT_STACK },
  { id: 'inter',     label: 'Neo Grotesk',    value: NEO_GROTESK_FONT_STACK },
  { id: 'geist',     label: 'Sharp Sans',     value: SHARP_SANS_FONT_STACK },
  { id: 'dmSans',    label: 'Humanist Sans',  value: HUMANIST_SANS_FONT_STACK },
  { id: 'manrope',   label: 'Display Sans',   value: DISPLAY_SANS_FONT_STACK },
  { id: 'outfit',    label: 'Wide Sans',      value: WIDE_SANS_FONT_STACK },
  { id: 'satoshi',   label: 'UI Sans',        value: UI_SANS_FONT_STACK },
  { id: 'jetbrains', label: 'JetBrains Mono', value: MONO_FONT_STACK },
  { id: 'georgia',   label: 'Georgia',        value: 'Georgia, "Times New Roman", serif' },
  { id: 'playfair',  label: 'Editorial Serif', value: EDITORIAL_SERIF_FONT_STACK },
] as const

/* ═══════════════════════════════════════════════════════════
   EASING OPTIONS
   ═══════════════════════════════════════════════════════════ */
export const EASING_OPTIONS = [
  { id: 'ease',                              label: 'Ease' },
  { id: 'ease-in-out',                       label: 'Ease In-Out' },
  { id: 'cubic-bezier(0.16,1,0.3,1)',        label: 'Spring' },
  { id: 'linear',                            label: 'Linear' },
  { id: 'cubic-bezier(0.33,1,0.68,1)',       label: 'Smooth Out' },
  { id: 'cubic-bezier(0.22,1,0.36,1)',       label: 'Expo Out' },
] as const

/* ═══════════════════════════════════════════════════════════
   TYPE SCALE PRESETS (ratio → name)
   ═══════════════════════════════════════════════════════════ */
export const TYPE_SCALE_OPTIONS = [
  { ratio: 1.067, label: 'Minor Second' },
  { ratio: 1.125, label: 'Major Second' },
  { ratio: 1.150, label: 'Custom 1.15' },
  { ratio: 1.200, label: 'Minor Third' },
  { ratio: 1.250, label: 'Major Third' },
  { ratio: 1.333, label: 'Perfect Fourth' },
  { ratio: 1.414, label: 'Aug. Fourth' },
  { ratio: 1.500, label: 'Perfect Fifth' },
] as const

/* ═══════════════════════════════════════════════════════════
   COMPOSABLE
   ═══════════════════════════════════════════════════════════ */
